"""Finite real Windows native preprobe identity and attribute custody regressions."""
import unittest
from . import test_windows_cp117_base_source_refresh as fixture

PREPROBE_OLD_IDENTITY_GUARD="if(($cp117CalTaskPin -join '|') -cne ($cp117CalTaskLast -join '|') -or ($cp117CalPythonPin -join '|') -cne ($cp117CalPythonLast -join '|') -or $cp117CalTaskResult.pythonResultSha256 -cne $cp117CalPythonPin[0] -or $cp117CalTaskResult.pythonResultIdentity -cne $cp117CalPythonPin[1]){throw 'PUBLISHER_RESULTS_DRIFT'}"
PREPROBE_OLD_TARGET_GUARD="$cp117SuccessorFile=[Cp117InstalledFile]::Read('C:\\Users\\vpncp117\\AppData\\Local\\VpnControl\\mcp-update-fixture-6d0bf26d-1708-4869-b9f3-c890d5719440\\content\\packages\\target\\vpn-control-2.2.2.msi');if($cp117SuccessorFile[0] -cne 'f8a8741bcfd22c04be50836aa22da77009105ab1b63df4d9b7648397779a8dfc' -or $cp117SuccessorFile[1] -cne '3996455293:589824:132627:692045065:31282495:0:131101044:32:691435522:31282495:1'){throw 'SERVER_SUCCESSOR_SOURCE_IDENTITY'}"
PREPROBE_CURRENT_TARGET_GUARD="$cp117SuccessorFile=[Cp117InstalledFile]::Read('C:\\Users\\vpncp117\\AppData\\Local\\VpnControl\\mcp-update-fixture-6d0bf26d-1708-4869-b9f3-c890d5719440\\content\\packages\\target\\vpn-control-2.2.2.msi');if($cp117SuccessorFile[0] -cne 'f8a8741bcfd22c04be50836aa22da77009105ab1b63df4d9b7648397779a8dfc' -or $cp117SuccessorFile[1] -cne $(if($script:cp117TargetAttributeRestored){'3996455293:589824:132627:692045065:31282495:0:131101044:33:691435522:31282495:1'}else{'3996455293:589824:132627:692045065:31282495:0:131101044:32:691435522:31282495:1'})){throw 'SERVER_SUCCESSOR_SOURCE_IDENTITY'}"
PREPROBE_FIXTURE_OLD_TARGET_GUARD="$cp117SuccessorFile=[Cp117InstalledFile]::Read($path);if($cp117SuccessorFile[0] -cne $before[0] -or $cp117SuccessorFile[1] -cne $before[1]){throw 'SERVER_SUCCESSOR_SOURCE_IDENTITY'}"
PREPROBE_FIXTURE_CURRENT_TARGET_GUARD="$cp117SuccessorFile=[Cp117InstalledFile]::Read($path);if($cp117SuccessorFile[0] -cne $before[0] -or $cp117SuccessorFile[1] -cne $(if($script:cp117TargetAttributeRestored){$after[1]}else{$before[1]})){throw 'SERVER_SUCCESSOR_SOURCE_IDENTITY'}"
class PreprobeIdentityOrderingTests(unittest.TestCase):
 @unittest.skipUnless(__import__('os').name=='nt','actual Windows native FileRow/InstalledFile identity producer consumer')
 def test_actual_native_producers_same_file_old_guard_refuses_ordered_roles(self):
  import tempfile
  from agent_tools import windows_cp117_base_source_refresh as worker
  ps=worker.installed.public._ps_literal
  script="$ErrorActionPreference='Stop';Add-Type -TypeDefinition "+ps(worker.WORKSPACE_CS)+" -ReferencedAssemblies @('System','System.Core');Add-Type -TypeDefinition "+ps(worker.installed.FILE_CS)+" -ReferencedAssemblies @('System','System.Core','System.IO.Compression');$root=Join-Path ([IO.Path]::GetTempPath()) ([Guid]::NewGuid().ToString());[IO.Directory]::CreateDirectory($root)|Out-Null;try{$path=Join-Path $root 'PUBLIC';[IO.File]::WriteAllBytes($path,[byte[]]@(65,66,67));$method=[Cp117RefreshWorkspace].GetMethod('FileRow',[Reflection.BindingFlags]'NonPublic,Static');$args=New-Object object[] 2;$args.SetValue([string]$path,0);$args.SetValue([long]3,1);$row=([string]$method.Invoke($null,$args)).Split([char]'|',3);$cp117CalPythonPin=[Cp117InstalledFile]::Read($path);$cp117CalPythonLast=[Cp117InstalledFile]::Read($path);$cp117CalTaskPin=@('PUBLIC','PUBLIC');$cp117CalTaskLast=@('PUBLIC','PUBLIC');$cp117CalTaskResult=@{pythonResultSha256=$row[1].ToLowerInvariant();pythonResultIdentity=$row[0]};$refused=$false;try{"+PREPROBE_OLD_IDENTITY_GUARD+"}catch{$refused=$_.Exception.Message -ceq 'PUBLISHER_RESULTS_DRIFT'};if(-not $refused){throw 'ACTUAL_OLD_REFUSAL_NOT_REPRODUCED'};$w=$row[0].Split(':');$i=$cp117CalPythonPin[1].Split(':');if($w.Count -ne 11 -or $i.Count -ne 11){throw 'NATIVE_FULL_SHAPE'};$mapped=@($i[0],$i[1],$i[2],$i[7],$i[8],$i[9],$i[3],$i[4],$i[5],$i[6],$i[10]);if(($w -join ':') -cne ($mapped -join ':') -or $row[1].ToLowerInvariant() -cne $cp117CalPythonPin[0]){throw 'NATIVE_ROLE_FIELDS_DIFFER'};'ACTUAL_ORDERED_ROLE_PRODUCERS_PASS'}finally{[IO.Directory]::Delete($root,$true)}"
  proc=fixture._run_complete_windows_fixture(script,timeout=20);self.assertEqual(proc.returncode,0,proc.stderr);self.assertIn(b'ACTUAL_ORDERED_ROLE_PRODUCERS_PASS',proc.stdout)
 @unittest.skipUnless(__import__('os').name=='nt','actual Windows held-file native identity attribute-only closure')
 def test_actual_held_native_pin_old_equality_refuses_attribute_only_projection(self):
  from agent_tools import windows_cp117_base_source_refresh as worker
  ps=worker.installed.public._ps_literal
  # Real exact InstalledFile producer + same expression as the measured old guard, own inert file only.
  script="$ErrorActionPreference='Stop';Add-Type -TypeDefinition "+ps(worker.installed.FILE_CS)+" -ReferencedAssemblies @('System','System.Core','System.IO.Compression');$root=Join-Path ([IO.Path]::GetTempPath()) ([Guid]::NewGuid().ToString());[IO.Directory]::CreateDirectory($root)|Out-Null;try{$path=Join-Path $root 'PUBLIC';[IO.File]::WriteAllBytes($path,[byte[]]@(65,66,67));[IO.File]::SetAttributes($path,[IO.FileAttributes]32);$before=[Cp117InstalledFile]::Read($path);$beforeSddl=[string](Get-Acl -LiteralPath $path).Sddl;$hold=[IO.FileStream]::new($path,[IO.FileMode]::Open,[IO.FileAccess]::Read,[IO.FileShare]::Read);try{$script:cp117TargetAttributeRestored=$false;"+PREPROBE_FIXTURE_OLD_TARGET_GUARD+PREPROBE_FIXTURE_CURRENT_TARGET_GUARD+";[IO.File]::SetAttributes($path,[IO.FileAttributes]33);$after=[Cp117InstalledFile]::Read($path);$oldRefused=$false;try{"+PREPROBE_FIXTURE_OLD_TARGET_GUARD+"}catch{$oldRefused=$_.Exception.Message -ceq 'SERVER_SUCCESSOR_SOURCE_IDENTITY'};if(-not $oldRefused){throw 'ACTUAL_OLD_POSTGUARD_NOT_RED'};$script:cp117TargetAttributeRestored=$true;"+PREPROBE_FIXTURE_CURRENT_TARGET_GUARD+";$script:cp117TargetAttributeRestored=$false;$wrongPhaseRefused=$false;try{"+PREPROBE_FIXTURE_CURRENT_TARGET_GUARD+"}catch{$wrongPhaseRefused=$_.Exception.Message -ceq 'SERVER_SUCCESSOR_SOURCE_IDENTITY'};if(-not $wrongPhaseRefused){throw 'WRONG_PHASE_ACCEPTED'};$fields=$before[1].Split(':');$fields[7]='33';if($after[1] -cne ($fields -join ':') -or $after[0] -cne $before[0] -or $beforeSddl -cne [string](Get-Acl -LiteralPath $path).Sddl){throw 'ATTRIBUTE_ONLY_CLOSURE'};'ATTRIBUTE_ONLY_NATIVE_GUARD_PASS'}finally{$hold.Dispose()}}finally{[IO.File]::SetAttributes($path,[IO.FileAttributes]32);[IO.Directory]::Delete($root,$true)}"
  proc=fixture._run_complete_windows_fixture(script,timeout=20);self.assertEqual(proc.returncode,0,proc.stderr);self.assertIn(b'ATTRIBUTE_ONLY_NATIVE_GUARD_PASS',proc.stdout)
