package com.kardinal.vpncontrol.shared.ui

import androidx.compose.runtime.Composable
import androidx.compose.runtime.compositionLocalOf
import androidx.compose.runtime.remember
import com.kardinal.vpncontrol.model.AppLanguage
import com.kardinal.vpncontrol.model.SubscriptionRefreshPolicy
import com.kardinal.vpncontrol.model.effective

enum class UiText {
    APP_TITLE,
    TAB_MAIN,
    TAB_PROFILE,
    TAB_LOCATIONS,
    TAB_STATS,
    TAB_RULES,
    MAIN_SUBSCRIPTION_DESCRIPTION,
    MAIN_SAVED_LOCATIONS_DESCRIPTION,
    CONNECT,
    DISCONNECT,
    START_PROXY,
    STOP_PROXY,
    VPN_PERMISSION_REQUIRED,
    VPN_CONNECT_DESCRIPTION,
    PROXY_CONNECT_DESCRIPTION,
    FIND_BEST,
    FIND_BEST_SUBSCRIPTION,
    FIND_BEST_SAVED,
    EXPORT_DIAGNOSTICS,
    STATUS,
    SELECTED_PROFILE,
    SELECTED_LOCATION,
    SERVER,
    MISMATCH_TITLE,
    MISMATCH_ACTIVE_PROFILE,
    MISMATCH_ACTION,
    PROFILE_TITLE,
    PROFILE_DESCRIPTION,
    CURRENT_SELECTION,
    STATS_TITLE,
    STATS_DESCRIPTION,
    SESSION,
    RUNNING_FOR,
    STOPPED,
    STARTED,
    SUCCESSFUL_STARTS_STOPS,
    CONNECTION_LOG,
    NO_RECENT_EVENTS,
    NEVER,
    SETTINGS_LANGUAGE,
    SETTINGS_LANGUAGE_SYSTEM,
    SETTINGS_LANGUAGE_DIALOG_TITLE,
    SETTINGS_LANGUAGE_DIALOG_DESCRIPTION,
    SETTINGS_CUSTOM_DNS,
    SETTINGS_START_ON_LOGIN,
    SETTINGS_VPN_PROXY_MODE,
    SETTINGS_PROXY_MODE,
    SETTINGS_SUBSCRIPTION_REFRESH,
    SETTINGS_LOCATION_TEST,
    SETTINGS_ENABLED,
    SETTINGS_DISABLED,
    SETTINGS_VPN_MODE,
    SETTINGS_PROXY_ONLY,
    SETTINGS_ALL_SUBSCRIPTIONS,
    SETTINGS_SELECTED_SUBSCRIPTION,
    SAVE,
    CANCEL,
    CLOSE,
    OK,
    USE_CUSTOM_DNS,
    DNS_APPLIES_NEW_DESKTOP_SESSIONS,
    DNS_IP_ADDRESS,
    APP_MODE_ANDROID_DESCRIPTION,
    APP_MODE_DESKTOP_DESCRIPTION,
    VPN,
    VPN_MODE_LABEL,
    PROXY_ONLY,
    APP_MODE_ANDROID_PROXY_DETAIL,
    APP_MODE_ANDROID_VPN_DETAIL,
    APP_MODE_ANDROID_VPN_FOOTER,
    APP_MODE_DESKTOP_VPN_DETAIL,
    APP_MODE_DESKTOP_PROXY_DETAIL,
    APP_MODE_DESKTOP_CHANGE_WARNING,
    REFRESH_DESCRIPTION_ALL,
    REFRESH_DESCRIPTION_SELECTED,
    REFRESH_DESCRIPTION_DESKTOP,
    REFRESH_POLICY_OFF,
    REFRESH_POLICY_HOURLY,
    REFRESH_POLICY_CUSTOM,
    REFRESH_POLICY_OFF_DESCRIPTION,
    REFRESH_POLICY_HOURLY_DESCRIPTION,
    REFRESH_POLICY_CUSTOM_DESCRIPTION,
    FIND_BEST_AFTER_REFRESH,
    KEEP_CURRENT_LOCATION_AFTER_REFRESH,
    FIND_BEST_AFTER_REFRESH_DESCRIPTION,
    KEEP_CURRENT_LOCATION_AFTER_REFRESH_DESCRIPTION,
    CUSTOM_INTERVAL_HOURS,
    CUSTOM_INTERVAL_HELP,
    VALIDATION_DESCRIPTION_ALL,
    VALIDATION_DESCRIPTION_SELECTED,
    VALIDATION_DESCRIPTION_DESKTOP,
    PRIMARY_TEST_SITE,
    SECONDARY_TEST_SITE,
    BATCH_SIZE,
    RETRY_COUNT,
    PRIMARY_TEST_SITE_PLACEHOLDER,
    SECONDARY_TEST_SITE_PLACEHOLDER,
    VALIDATION_ANDROID_SUMMARY,
    VALIDATION_DESKTOP_SUMMARY,
}

class AppStrings(
    val language: AppLanguage,
) {
    fun get(key: UiText): String = translations[language]?.get(key)
        ?: translations[AppLanguage.ENGLISH]?.get(key)
        ?: key.name

    fun format(key: UiText, vararg args: Any?): String {
        var text = get(key)
        args.forEachIndexed { index, value ->
            text = text.replace("{$index}", value?.toString().orEmpty())
        }
        return text
    }

    fun languageDisplayName(language: AppLanguage, systemLanguageCode: String? = null): String {
        return if (language == AppLanguage.SYSTEM) {
            "${get(UiText.SETTINGS_LANGUAGE_SYSTEM)} (${language.effective(systemLanguageCode).nativeName})"
        } else {
            language.nativeName
        }
    }

    fun refreshPolicyTitle(policy: SubscriptionRefreshPolicy): String {
        return when (policy) {
            SubscriptionRefreshPolicy.OFF -> get(UiText.REFRESH_POLICY_OFF)
            SubscriptionRefreshPolicy.EVERY_HOUR -> get(UiText.REFRESH_POLICY_HOURLY)
            SubscriptionRefreshPolicy.CUSTOM -> get(UiText.REFRESH_POLICY_CUSTOM)
        }
    }

    fun refreshPolicyDisplay(policy: SubscriptionRefreshPolicy, customIntervalHours: Double): String {
        return when (policy) {
            SubscriptionRefreshPolicy.OFF,
            SubscriptionRefreshPolicy.EVERY_HOUR,
            -> refreshPolicyTitle(policy)
            SubscriptionRefreshPolicy.CUSTOM -> "${refreshPolicyTitle(policy)} (${customIntervalHours}h)"
        }
    }
}

val LocalAppStrings = compositionLocalOf { AppStrings(AppLanguage.ENGLISH) }

@Composable
fun rememberAppStrings(
    languageOverride: AppLanguage,
    systemLanguageCode: String?,
): AppStrings {
    val effective = languageOverride.effective(systemLanguageCode)
    return remember(effective) { AppStrings(effective) }
}

private val en = mapOf(
    UiText.APP_TITLE to "VPN Control",
    UiText.TAB_MAIN to "Main",
    UiText.TAB_PROFILE to "Profile",
    UiText.TAB_LOCATIONS to "Locations",
    UiText.TAB_STATS to "Stats",
    UiText.TAB_RULES to "Rules",
    UiText.MAIN_SUBSCRIPTION_DESCRIPTION to "Subscription mode is active. Finding the best location downloads locations from the remote source and updates the saved list.",
    UiText.MAIN_SAVED_LOCATIONS_DESCRIPTION to "Saved locations are active. Finding the best location tests the locations saved on the Locations tab.",
    UiText.CONNECT to "Connect",
    UiText.DISCONNECT to "Disconnect",
    UiText.START_PROXY to "Start Proxy",
    UiText.STOP_PROXY to "Stop Proxy",
    UiText.VPN_PERMISSION_REQUIRED to "VPN permission required",
    UiText.VPN_CONNECT_DESCRIPTION to "Connect or disconnect the VPN",
    UiText.PROXY_CONNECT_DESCRIPTION to "Start or stop the local mixed proxy",
    UiText.FIND_BEST to "Find Best",
    UiText.FIND_BEST_SUBSCRIPTION to "Find the best location from the subscription",
    UiText.FIND_BEST_SAVED to "Find the best location from saved locations",
    UiText.EXPORT_DIAGNOSTICS to "Export Diagnostics",
    UiText.STATUS to "Status",
    UiText.SELECTED_PROFILE to "Selected profile: {0}",
    UiText.SELECTED_LOCATION to "Selected location: {0}",
    UiText.SERVER to "Server: {0}",
    UiText.MISMATCH_TITLE to "Selected location is from a different subscription",
    UiText.MISMATCH_ACTIVE_PROFILE to "Active profile: {0}",
    UiText.MISMATCH_ACTION to "Run Find Best or reconnect to switch to a location from the current subscription.",
    UiText.PROFILE_TITLE to "Profile",
    UiText.PROFILE_DESCRIPTION to "Choose where the app gets locations from. Use a remote source in subscription mode, or work only with the saved list from the Locations tab.",
    UiText.CURRENT_SELECTION to "Current selection: {0}",
    UiText.STATS_TITLE to "Stats",
    UiText.STATS_DESCRIPTION to "Session data and recent status history are shown here.",
    UiText.SESSION to "Session",
    UiText.RUNNING_FOR to "Running for {0}",
    UiText.STOPPED to "Stopped",
    UiText.STARTED to "Started: {0}",
    UiText.SUCCESSFUL_STARTS_STOPS to "Successful starts: {0} • Successful stops: {1}",
    UiText.CONNECTION_LOG to "Connection Log",
    UiText.NO_RECENT_EVENTS to "No recent events yet.",
    UiText.NEVER to "never",
    UiText.SETTINGS_LANGUAGE to "Language",
    UiText.SETTINGS_LANGUAGE_SYSTEM to "System",
    UiText.SETTINGS_LANGUAGE_DIALOG_TITLE to "Language",
    UiText.SETTINGS_LANGUAGE_DIALOG_DESCRIPTION to "Use the system language by default, or choose a language for VPN Control only.",
    UiText.SETTINGS_CUSTOM_DNS to "Custom DNS",
    UiText.SETTINGS_START_ON_LOGIN to "Start on Login",
    UiText.SETTINGS_VPN_PROXY_MODE to "VPN / Proxy Mode",
    UiText.SETTINGS_PROXY_MODE to "Proxy Mode Settings",
    UiText.SETTINGS_SUBSCRIPTION_REFRESH to "Subscription Auto-Refresh",
    UiText.SETTINGS_LOCATION_TEST to "Location Test Settings",
    UiText.SETTINGS_ENABLED to "enabled",
    UiText.SETTINGS_DISABLED to "disabled",
    UiText.SETTINGS_VPN_MODE to "VPN mode",
    UiText.SETTINGS_PROXY_ONLY to "Proxy-only mode",
    UiText.SETTINGS_ALL_SUBSCRIPTIONS to "all subscriptions",
    UiText.SETTINGS_SELECTED_SUBSCRIPTION to "selected subscription",
    UiText.SAVE to "Save",
    UiText.CANCEL to "Cancel",
    UiText.CLOSE to "Close",
    UiText.OK to "OK",
    UiText.USE_CUSTOM_DNS to "Use custom DNS",
    UiText.DNS_APPLIES_NEW_DESKTOP_SESSIONS to "Applies to new desktop proxy or VPN sessions.",
    UiText.DNS_IP_ADDRESS to "DNS IP address",
    UiText.APP_MODE_ANDROID_DESCRIPTION to "Default mode is VPN. Turn on Proxy Only to run a local HTTP/SOCKS mixed proxy instead of Android VPN.",
    UiText.APP_MODE_DESKTOP_DESCRIPTION to "VPN mode uses sing-box TUN on Linux or Windows. macOS currently supports Proxy-only mode until a privileged helper is implemented.",
    UiText.VPN to "VPN",
    UiText.VPN_MODE_LABEL to "VPN Mode",
    UiText.PROXY_ONLY to "Proxy Only",
    UiText.APP_MODE_ANDROID_PROXY_DETAIL to "Local mixed proxy mode is enabled. Turn it off to use Android VPN mode.",
    UiText.APP_MODE_ANDROID_VPN_DETAIL to "Android VPN mode is enabled. Turn on Proxy Only to expose a local mixed proxy instead.",
    UiText.APP_MODE_ANDROID_VPN_FOOTER to "VPN mode routes traffic through Android VpnService.",
    UiText.APP_MODE_DESKTOP_VPN_DETAIL to "Turn off to use only the local proxy.",
    UiText.APP_MODE_DESKTOP_PROXY_DETAIL to "Turn on to route desktop traffic through VPN/TUN mode.",
    UiText.APP_MODE_DESKTOP_CHANGE_WARNING to "Changing mode while connected stops the current session first.",
    UiText.REFRESH_DESCRIPTION_ALL to "Works only when Profile Source is set to Subscription. The app will periodically redownload every saved subscription and update the merged locations list.",
    UiText.REFRESH_DESCRIPTION_SELECTED to "Works only when Profile Source is set to Subscription. The app will periodically redownload the selected subscription and update the saved locations list.",
    UiText.REFRESH_DESCRIPTION_DESKTOP to "While the desktop app is open, it can periodically redownload {0} and update cached locations.",
    UiText.REFRESH_POLICY_OFF to "Off",
    UiText.REFRESH_POLICY_HOURLY to "Every hour",
    UiText.REFRESH_POLICY_CUSTOM to "Custom interval",
    UiText.REFRESH_POLICY_OFF_DESCRIPTION to "Do not update subscriptions in the background.",
    UiText.REFRESH_POLICY_HOURLY_DESCRIPTION to "Refresh cached locations every hour.",
    UiText.REFRESH_POLICY_CUSTOM_DESCRIPTION to "Use a custom interval in hours. Minimum 5 minutes.",
    UiText.FIND_BEST_AFTER_REFRESH to "Find best after refresh",
    UiText.KEEP_CURRENT_LOCATION_AFTER_REFRESH to "Keep current location after refresh",
    UiText.FIND_BEST_AFTER_REFRESH_DESCRIPTION to "When already connected, rerun best-location search after a background refresh finishes.",
    UiText.KEEP_CURRENT_LOCATION_AFTER_REFRESH_DESCRIPTION to "Background refresh only updates subscription caches and does not rerun best-location search.",
    UiText.CUSTOM_INTERVAL_HOURS to "Custom interval (hours)",
    UiText.CUSTOM_INTERVAL_HELP to "Examples: 0.5 = 30 minutes, 1.5 = 1 h 30 min. Minimum 5 minutes.",
    UiText.VALIDATION_DESCRIPTION_ALL to "The app uses these sites when testing locations. In All mode it checks the fastest locations from every saved subscription in batches: top N first, then the next N, until the secondary site works.",
    UiText.VALIDATION_DESCRIPTION_SELECTED to "The app uses these sites when testing locations. In subscription mode it checks the fastest locations from the selected subscription in batches: top N first, then the next N, until the secondary site works.",
    UiText.VALIDATION_DESCRIPTION_DESKTOP to "Find best uses these sites when testing locations from {0}.",
    UiText.PRIMARY_TEST_SITE to "Primary test site",
    UiText.SECONDARY_TEST_SITE to "Secondary test site",
    UiText.BATCH_SIZE to "Batch size",
    UiText.RETRY_COUNT to "Retry count",
    UiText.PRIMARY_TEST_SITE_PLACEHOLDER to "google.com or full URL",
    UiText.SECONDARY_TEST_SITE_PLACEHOLDER to "secondary-site.com or full URL",
    UiText.VALIDATION_ANDROID_SUMMARY to "Concurrency matches the current batch size, up to 5. Retry count reruns the whole search if no usable location is found. Current settings: {0}",
    UiText.VALIDATION_DESKTOP_SUMMARY to "Concurrency matches batch size, up to 5. Current: {0}",
)

private val translations: Map<AppLanguage, Map<UiText, String>> = mapOf(
    AppLanguage.ENGLISH to en,
    AppLanguage.RUSSIAN to en + mapOf(
        UiText.TAB_MAIN to "Главная",
        UiText.TAB_PROFILE to "Профиль",
        UiText.TAB_LOCATIONS to "Локации",
        UiText.TAB_STATS to "Статистика",
        UiText.TAB_RULES to "Правила",
        UiText.MAIN_SUBSCRIPTION_DESCRIPTION to "Активен режим подписки. Поиск лучшей локации загружает локации из удаленного источника и обновляет сохраненный список.",
        UiText.MAIN_SAVED_LOCATIONS_DESCRIPTION to "Активны сохраненные локации. Поиск лучшей локации проверяет локации из вкладки Локации.",
        UiText.CONNECT to "Подключить",
        UiText.DISCONNECT to "Отключить",
        UiText.START_PROXY to "Запустить прокси",
        UiText.STOP_PROXY to "Остановить прокси",
        UiText.VPN_PERMISSION_REQUIRED to "Нужно разрешение VPN",
        UiText.VPN_CONNECT_DESCRIPTION to "Подключить или отключить VPN",
        UiText.PROXY_CONNECT_DESCRIPTION to "Запустить или остановить локальный прокси",
        UiText.FIND_BEST to "Найти лучшую",
        UiText.FIND_BEST_SUBSCRIPTION to "Найти лучшую локацию из подписки",
        UiText.FIND_BEST_SAVED to "Найти лучшую сохраненную локацию",
        UiText.EXPORT_DIAGNOSTICS to "Экспорт диагностики",
        UiText.STATUS to "Статус",
        UiText.SELECTED_PROFILE to "Выбранный профиль: {0}",
        UiText.SELECTED_LOCATION to "Выбранная локация: {0}",
        UiText.SERVER to "Сервер: {0}",
        UiText.MISMATCH_TITLE to "Выбранная локация из другой подписки",
        UiText.MISMATCH_ACTIVE_PROFILE to "Активный профиль: {0}",
        UiText.MISMATCH_ACTION to "Запустите поиск лучшей локации или переподключитесь.",
        UiText.PROFILE_TITLE to "Профиль",
        UiText.PROFILE_DESCRIPTION to "Выберите источник локаций: удаленная подписка или сохраненный список.",
        UiText.CURRENT_SELECTION to "Текущий выбор: {0}",
        UiText.STATS_TITLE to "Статистика",
        UiText.STATS_DESCRIPTION to "Данные сессии и последние события.",
        UiText.SESSION to "Сессия",
        UiText.RUNNING_FOR to "Работает {0}",
        UiText.STOPPED to "Остановлено",
        UiText.STARTED to "Запущено: {0}",
        UiText.SUCCESSFUL_STARTS_STOPS to "Успешные запуски: {0} • остановки: {1}",
        UiText.CONNECTION_LOG to "Журнал подключения",
        UiText.NO_RECENT_EVENTS to "Событий пока нет.",
        UiText.NEVER to "никогда",
        UiText.SETTINGS_LANGUAGE to "Язык",
        UiText.SETTINGS_LANGUAGE_SYSTEM to "Системный",
        UiText.SETTINGS_LANGUAGE_DIALOG_TITLE to "Язык",
        UiText.SETTINGS_LANGUAGE_DIALOG_DESCRIPTION to "Используйте язык системы или выберите язык только для VPN Control.",
        UiText.SETTINGS_CUSTOM_DNS to "Пользовательский DNS",
        UiText.SETTINGS_START_ON_LOGIN to "Запуск при входе",
        UiText.SETTINGS_VPN_PROXY_MODE to "VPN / прокси",
        UiText.SETTINGS_PROXY_MODE to "Режим прокси",
        UiText.SETTINGS_SUBSCRIPTION_REFRESH to "Автообновление подписки",
        UiText.SETTINGS_LOCATION_TEST to "Проверка локаций",
        UiText.SETTINGS_ENABLED to "включено",
        UiText.SETTINGS_DISABLED to "выключено",
        UiText.SETTINGS_VPN_MODE to "режим VPN",
        UiText.SETTINGS_PROXY_ONLY to "только прокси",
        UiText.SETTINGS_ALL_SUBSCRIPTIONS to "все подписки",
        UiText.SETTINGS_SELECTED_SUBSCRIPTION to "выбранная подписка",
        UiText.SAVE to "Сохранить",
        UiText.CANCEL to "Отмена",
        UiText.CLOSE to "Закрыть",
        UiText.OK to "ОК",
        UiText.USE_CUSTOM_DNS to "Использовать пользовательский DNS",
        UiText.DNS_APPLIES_NEW_DESKTOP_SESSIONS to "Применяется к новым desktop-сессиям прокси или VPN.",
        UiText.DNS_IP_ADDRESS to "IP-адрес DNS",
        UiText.APP_MODE_ANDROID_DESCRIPTION to "Режим по умолчанию - VPN. Включите только прокси, чтобы запустить локальный HTTP/SOCKS mixed proxy вместо Android VPN.",
        UiText.APP_MODE_DESKTOP_DESCRIPTION to "Режим VPN использует sing-box TUN на Linux или Windows. macOS пока поддерживает только прокси, пока не будет добавлен privileged helper.",
        UiText.VPN to "VPN",
        UiText.VPN_MODE_LABEL to "Режим VPN",
        UiText.PROXY_ONLY to "Только прокси",
        UiText.APP_MODE_ANDROID_PROXY_DETAIL to "Включен локальный mixed proxy. Отключите его, чтобы использовать Android VPN.",
        UiText.APP_MODE_ANDROID_VPN_DETAIL to "Включен Android VPN. Включите только прокси, чтобы открыть локальный mixed proxy.",
        UiText.APP_MODE_ANDROID_VPN_FOOTER to "Режим VPN направляет трафик через Android VpnService.",
        UiText.APP_MODE_DESKTOP_VPN_DETAIL to "Отключите, чтобы использовать только локальный прокси.",
        UiText.APP_MODE_DESKTOP_PROXY_DETAIL to "Включите, чтобы направлять desktop-трафик через режим VPN/TUN.",
        UiText.APP_MODE_DESKTOP_CHANGE_WARNING to "Смена режима при активном подключении сначала остановит текущую сессию.",
        UiText.REFRESH_DESCRIPTION_ALL to "Работает только когда источник профиля - подписка. Приложение будет периодически перезагружать все сохраненные подписки и обновлять объединенный список локаций.",
        UiText.REFRESH_DESCRIPTION_SELECTED to "Работает только когда источник профиля - подписка. Приложение будет периодически перезагружать выбранную подписку и обновлять список сохраненных локаций.",
        UiText.REFRESH_DESCRIPTION_DESKTOP to "Пока desktop-приложение открыто, оно может периодически перезагружать {0} и обновлять кэш локаций.",
        UiText.REFRESH_POLICY_OFF to "Выключено",
        UiText.REFRESH_POLICY_HOURLY to "Каждый час",
        UiText.REFRESH_POLICY_CUSTOM to "Свой интервал",
        UiText.REFRESH_POLICY_OFF_DESCRIPTION to "Не обновлять подписки в фоне.",
        UiText.REFRESH_POLICY_HOURLY_DESCRIPTION to "Обновлять кэш локаций каждый час.",
        UiText.REFRESH_POLICY_CUSTOM_DESCRIPTION to "Использовать свой интервал в часах. Минимум 5 минут.",
        UiText.FIND_BEST_AFTER_REFRESH to "Искать лучшую после обновления",
        UiText.KEEP_CURRENT_LOCATION_AFTER_REFRESH to "Оставлять текущую локацию",
        UiText.FIND_BEST_AFTER_REFRESH_DESCRIPTION to "Если уже подключено, после фонового обновления заново выполнить поиск лучшей локации.",
        UiText.KEEP_CURRENT_LOCATION_AFTER_REFRESH_DESCRIPTION to "Фоновое обновление только обновляет кэш подписок и не запускает поиск лучшей локации.",
        UiText.CUSTOM_INTERVAL_HOURS to "Свой интервал (часы)",
        UiText.CUSTOM_INTERVAL_HELP to "Примеры: 0.5 = 30 минут, 1.5 = 1 ч 30 мин. Минимум 5 минут.",
        UiText.VALIDATION_DESCRIPTION_ALL to "Приложение использует эти сайты при проверке локаций. В режиме All оно проверяет самые быстрые локации из всех сохраненных подписок пачками: сначала top N, затем следующие N, пока вторичный сайт не заработает.",
        UiText.VALIDATION_DESCRIPTION_SELECTED to "Приложение использует эти сайты при проверке локаций. В режиме подписки оно проверяет самые быстрые локации из выбранной подписки пачками: сначала top N, затем следующие N, пока вторичный сайт не заработает.",
        UiText.VALIDATION_DESCRIPTION_DESKTOP to "Find best использует эти сайты при проверке локаций из {0}.",
        UiText.PRIMARY_TEST_SITE to "Основной тестовый сайт",
        UiText.SECONDARY_TEST_SITE to "Вторичный тестовый сайт",
        UiText.BATCH_SIZE to "Размер пачки",
        UiText.RETRY_COUNT to "Количество повторов",
        UiText.PRIMARY_TEST_SITE_PLACEHOLDER to "google.com или полный URL",
        UiText.SECONDARY_TEST_SITE_PLACEHOLDER to "secondary-site.com или полный URL",
        UiText.VALIDATION_ANDROID_SUMMARY to "Параллелизм равен текущему размеру пачки, максимум 5. Повторы перезапускают весь поиск, если рабочая локация не найдена. Текущие настройки: {0}",
        UiText.VALIDATION_DESKTOP_SUMMARY to "Параллелизм равен размеру пачки, максимум 5. Сейчас: {0}",
    ),
    AppLanguage.GERMAN to en + mapOf(
        UiText.TAB_MAIN to "Start",
        UiText.TAB_PROFILE to "Profil",
        UiText.TAB_LOCATIONS to "Standorte",
        UiText.TAB_STATS to "Statistik",
        UiText.TAB_RULES to "Regeln",
        UiText.CONNECT to "Verbinden",
        UiText.DISCONNECT to "Trennen",
        UiText.FIND_BEST to "Beste finden",
        UiText.EXPORT_DIAGNOSTICS to "Diagnose exportieren",
        UiText.STATUS to "Status",
        UiText.PROFILE_TITLE to "Profil",
        UiText.STATS_TITLE to "Statistik",
        UiText.SETTINGS_LANGUAGE to "Sprache",
        UiText.SETTINGS_LANGUAGE_SYSTEM to "System",
        UiText.SETTINGS_CUSTOM_DNS to "Benutzerdefiniertes DNS",
        UiText.SETTINGS_START_ON_LOGIN to "Beim Anmelden starten",
        UiText.SETTINGS_VPN_PROXY_MODE to "VPN / Proxy",
        UiText.SETTINGS_SUBSCRIPTION_REFRESH to "Abo automatisch aktualisieren",
        UiText.SETTINGS_LOCATION_TEST to "Standorttests",
        UiText.SETTINGS_ENABLED to "aktiviert",
        UiText.SETTINGS_DISABLED to "deaktiviert",
        UiText.SAVE to "Speichern",
        UiText.CANCEL to "Abbrechen",
        UiText.CLOSE to "Schließen",
        UiText.OK to "OK",
        UiText.USE_CUSTOM_DNS to "Benutzerdefiniertes DNS verwenden",
        UiText.DNS_IP_ADDRESS to "DNS-IP-Adresse",
        UiText.VPN to "VPN",
        UiText.VPN_MODE_LABEL to "VPN-Modus",
        UiText.PROXY_ONLY to "Nur Proxy",
        UiText.REFRESH_POLICY_OFF to "Aus",
        UiText.REFRESH_POLICY_HOURLY to "Jede Stunde",
        UiText.REFRESH_POLICY_CUSTOM to "Benutzerdefiniertes Intervall",
        UiText.FIND_BEST_AFTER_REFRESH to "Beste nach Aktualisierung finden",
        UiText.KEEP_CURRENT_LOCATION_AFTER_REFRESH to "Aktuellen Standort behalten",
        UiText.CUSTOM_INTERVAL_HOURS to "Intervall (Stunden)",
        UiText.PRIMARY_TEST_SITE to "Primäre Testseite",
        UiText.SECONDARY_TEST_SITE to "Sekundäre Testseite",
        UiText.BATCH_SIZE to "Batchgröße",
        UiText.RETRY_COUNT to "Wiederholungen",
    ),
    AppLanguage.CHINESE to en + mapOf(
        UiText.TAB_MAIN to "主页",
        UiText.TAB_PROFILE to "配置",
        UiText.TAB_LOCATIONS to "节点",
        UiText.TAB_STATS to "统计",
        UiText.TAB_RULES to "规则",
        UiText.CONNECT to "连接",
        UiText.DISCONNECT to "断开",
        UiText.FIND_BEST to "寻找最佳",
        UiText.EXPORT_DIAGNOSTICS to "导出诊断",
        UiText.STATUS to "状态",
        UiText.PROFILE_TITLE to "配置",
        UiText.STATS_TITLE to "统计",
        UiText.SETTINGS_LANGUAGE to "语言",
        UiText.SETTINGS_LANGUAGE_SYSTEM to "系统",
        UiText.SETTINGS_CUSTOM_DNS to "自定义 DNS",
        UiText.SETTINGS_START_ON_LOGIN to "登录时启动",
        UiText.SETTINGS_VPN_PROXY_MODE to "VPN / 代理",
        UiText.SETTINGS_SUBSCRIPTION_REFRESH to "订阅自动刷新",
        UiText.SETTINGS_LOCATION_TEST to "节点测试设置",
        UiText.SETTINGS_ENABLED to "已启用",
        UiText.SETTINGS_DISABLED to "已禁用",
        UiText.SAVE to "保存",
        UiText.CANCEL to "取消",
        UiText.CLOSE to "关闭",
        UiText.OK to "确定",
        UiText.USE_CUSTOM_DNS to "使用自定义 DNS",
        UiText.DNS_IP_ADDRESS to "DNS IP 地址",
        UiText.VPN to "VPN",
        UiText.VPN_MODE_LABEL to "VPN 模式",
        UiText.PROXY_ONLY to "仅代理",
        UiText.REFRESH_POLICY_OFF to "关闭",
        UiText.REFRESH_POLICY_HOURLY to "每小时",
        UiText.REFRESH_POLICY_CUSTOM to "自定义间隔",
        UiText.FIND_BEST_AFTER_REFRESH to "刷新后寻找最佳",
        UiText.KEEP_CURRENT_LOCATION_AFTER_REFRESH to "保留当前节点",
        UiText.CUSTOM_INTERVAL_HOURS to "自定义间隔（小时）",
        UiText.PRIMARY_TEST_SITE to "主测试站点",
        UiText.SECONDARY_TEST_SITE to "备用测试站点",
        UiText.BATCH_SIZE to "批大小",
        UiText.RETRY_COUNT to "重试次数",
    ),
    AppLanguage.SPANISH to en + mapOf(
        UiText.TAB_MAIN to "Inicio",
        UiText.TAB_PROFILE to "Perfil",
        UiText.TAB_LOCATIONS to "Ubicaciones",
        UiText.TAB_STATS to "Estadísticas",
        UiText.TAB_RULES to "Reglas",
        UiText.CONNECT to "Conectar",
        UiText.DISCONNECT to "Desconectar",
        UiText.FIND_BEST to "Buscar mejor",
        UiText.EXPORT_DIAGNOSTICS to "Exportar diagnóstico",
        UiText.STATUS to "Estado",
        UiText.PROFILE_TITLE to "Perfil",
        UiText.STATS_TITLE to "Estadísticas",
        UiText.SETTINGS_LANGUAGE to "Idioma",
        UiText.SETTINGS_LANGUAGE_SYSTEM to "Sistema",
        UiText.SETTINGS_CUSTOM_DNS to "DNS personalizado",
        UiText.SETTINGS_START_ON_LOGIN to "Iniciar al entrar",
        UiText.SETTINGS_VPN_PROXY_MODE to "VPN / Proxy",
        UiText.SETTINGS_SUBSCRIPTION_REFRESH to "Actualización automática",
        UiText.SETTINGS_LOCATION_TEST to "Prueba de ubicaciones",
        UiText.SETTINGS_ENABLED to "activado",
        UiText.SETTINGS_DISABLED to "desactivado",
        UiText.SAVE to "Guardar",
        UiText.CANCEL to "Cancelar",
        UiText.CLOSE to "Cerrar",
        UiText.OK to "OK",
        UiText.USE_CUSTOM_DNS to "Usar DNS personalizado",
        UiText.DNS_IP_ADDRESS to "Dirección IP DNS",
        UiText.VPN to "VPN",
        UiText.VPN_MODE_LABEL to "Modo VPN",
        UiText.PROXY_ONLY to "Solo proxy",
        UiText.REFRESH_POLICY_OFF to "Apagado",
        UiText.REFRESH_POLICY_HOURLY to "Cada hora",
        UiText.REFRESH_POLICY_CUSTOM to "Intervalo personalizado",
        UiText.FIND_BEST_AFTER_REFRESH to "Buscar mejor tras actualizar",
        UiText.KEEP_CURRENT_LOCATION_AFTER_REFRESH to "Mantener ubicación actual",
        UiText.CUSTOM_INTERVAL_HOURS to "Intervalo personalizado (horas)",
        UiText.PRIMARY_TEST_SITE to "Sitio de prueba principal",
        UiText.SECONDARY_TEST_SITE to "Sitio de prueba secundario",
        UiText.BATCH_SIZE to "Tamaño de lote",
        UiText.RETRY_COUNT to "Reintentos",
    ),
    AppLanguage.PORTUGUESE to en + mapOf(
        UiText.TAB_MAIN to "Início",
        UiText.TAB_PROFILE to "Perfil",
        UiText.TAB_LOCATIONS to "Localizações",
        UiText.TAB_STATS to "Estatísticas",
        UiText.TAB_RULES to "Regras",
        UiText.CONNECT to "Conectar",
        UiText.DISCONNECT to "Desconectar",
        UiText.FIND_BEST to "Encontrar melhor",
        UiText.EXPORT_DIAGNOSTICS to "Exportar diagnóstico",
        UiText.STATUS to "Estado",
        UiText.PROFILE_TITLE to "Perfil",
        UiText.STATS_TITLE to "Estatísticas",
        UiText.SETTINGS_LANGUAGE to "Idioma",
        UiText.SETTINGS_LANGUAGE_SYSTEM to "Sistema",
        UiText.SETTINGS_CUSTOM_DNS to "DNS personalizado",
        UiText.SETTINGS_START_ON_LOGIN to "Iniciar ao entrar",
        UiText.SETTINGS_VPN_PROXY_MODE to "VPN / Proxy",
        UiText.SETTINGS_SUBSCRIPTION_REFRESH to "Atualização automática",
        UiText.SETTINGS_LOCATION_TEST to "Teste de localizações",
        UiText.SETTINGS_ENABLED to "ativado",
        UiText.SETTINGS_DISABLED to "desativado",
        UiText.SAVE to "Salvar",
        UiText.CANCEL to "Cancelar",
        UiText.CLOSE to "Fechar",
        UiText.OK to "OK",
        UiText.USE_CUSTOM_DNS to "Usar DNS personalizado",
        UiText.DNS_IP_ADDRESS to "Endereço IP do DNS",
        UiText.VPN to "VPN",
        UiText.VPN_MODE_LABEL to "Modo VPN",
        UiText.PROXY_ONLY to "Somente proxy",
        UiText.REFRESH_POLICY_OFF to "Desligado",
        UiText.REFRESH_POLICY_HOURLY to "A cada hora",
        UiText.REFRESH_POLICY_CUSTOM to "Intervalo personalizado",
        UiText.FIND_BEST_AFTER_REFRESH to "Encontrar melhor após atualizar",
        UiText.KEEP_CURRENT_LOCATION_AFTER_REFRESH to "Manter localização atual",
        UiText.CUSTOM_INTERVAL_HOURS to "Intervalo personalizado (horas)",
        UiText.PRIMARY_TEST_SITE to "Site de teste primário",
        UiText.SECONDARY_TEST_SITE to "Site de teste secundário",
        UiText.BATCH_SIZE to "Tamanho do lote",
        UiText.RETRY_COUNT to "Tentativas",
    ),
    AppLanguage.FRENCH to en + mapOf(
        UiText.TAB_MAIN to "Accueil",
        UiText.TAB_PROFILE to "Profil",
        UiText.TAB_LOCATIONS to "Emplacements",
        UiText.TAB_STATS to "Stats",
        UiText.TAB_RULES to "Règles",
        UiText.CONNECT to "Connecter",
        UiText.DISCONNECT to "Déconnecter",
        UiText.FIND_BEST to "Trouver le meilleur",
        UiText.EXPORT_DIAGNOSTICS to "Exporter le diagnostic",
        UiText.STATUS to "État",
        UiText.PROFILE_TITLE to "Profil",
        UiText.STATS_TITLE to "Stats",
        UiText.SETTINGS_LANGUAGE to "Langue",
        UiText.SETTINGS_LANGUAGE_SYSTEM to "Système",
        UiText.SETTINGS_CUSTOM_DNS to "DNS personnalisé",
        UiText.SETTINGS_START_ON_LOGIN to "Lancer à la connexion",
        UiText.SETTINGS_VPN_PROXY_MODE to "VPN / Proxy",
        UiText.SETTINGS_SUBSCRIPTION_REFRESH to "Actualisation automatique",
        UiText.SETTINGS_LOCATION_TEST to "Tests des emplacements",
        UiText.SETTINGS_ENABLED to "activé",
        UiText.SETTINGS_DISABLED to "désactivé",
        UiText.SAVE to "Enregistrer",
        UiText.CANCEL to "Annuler",
        UiText.CLOSE to "Fermer",
        UiText.OK to "OK",
        UiText.USE_CUSTOM_DNS to "Utiliser un DNS personnalisé",
        UiText.DNS_IP_ADDRESS to "Adresse IP DNS",
        UiText.VPN to "VPN",
        UiText.VPN_MODE_LABEL to "Mode VPN",
        UiText.PROXY_ONLY to "Proxy uniquement",
        UiText.REFRESH_POLICY_OFF to "Désactivé",
        UiText.REFRESH_POLICY_HOURLY to "Toutes les heures",
        UiText.REFRESH_POLICY_CUSTOM to "Intervalle personnalisé",
        UiText.FIND_BEST_AFTER_REFRESH to "Trouver le meilleur après actualisation",
        UiText.KEEP_CURRENT_LOCATION_AFTER_REFRESH to "Garder l'emplacement actuel",
        UiText.CUSTOM_INTERVAL_HOURS to "Intervalle personnalisé (heures)",
        UiText.PRIMARY_TEST_SITE to "Site de test principal",
        UiText.SECONDARY_TEST_SITE to "Site de test secondaire",
        UiText.BATCH_SIZE to "Taille du lot",
        UiText.RETRY_COUNT to "Relances",
    ),
)
