package com.kardinal.vpncontrol.shared.ui

import com.kardinal.vpncontrol.model.AppLanguage

internal fun localizedFreeformTextSupplement(language: AppLanguage, text: String): String? {
    val replacements = supplementalFreeformTextTranslations[language] ?: return null
    val translated = replacements.fold(text) { current, (source, target) ->
        current.replace(source, target)
    }
    return translated.takeIf { it != text }
}

private val supplementalFreeformTextTranslations: Map<AppLanguage, List<Pair<String, String>>> = mapOf(
    AppLanguage.RUSSIAN to listOf(
        "Subscription URL" to "URL подписки",
        "Unreadable subscription URL" to "Нечитаемый URL подписки",
        "Insecure HTTP subscriptions are not supported" to "Небезопасные HTTP-подписки не поддерживаются",
        "Use an https:// subscription URL." to "Используйте URL подписки https://.",
        "The URL must include a valid HTTPS host" to "URL должен содержать корректный HTTPS-хост",
        "Paste a valid https:// subscription URL." to "Вставьте корректный URL подписки https://.",
        "Direct remote source" to "Прямой удаленный источник",
        "sing-box import link" to "ссылка импорта sing-box",
        "Unreadable sing-box import link" to "Нечитаемая ссылка импорта sing-box",
        "Only valid HTTPS remote URLs are supported" to "Поддерживаются только корректные удаленные HTTPS URL",
        "Use a sing-box import link that resolves to a valid https:// URL." to "Используйте ссылку импорта sing-box, которая ведет к корректному URL https://.",
        "Fetches remote content from the embedded URL" to "Загружает удаленный контент из встроенного URL",
        "Fetches remote content from " to "Загружает удаленный контент с ",
        "The import link could not be parsed" to "Ссылку импорта не удалось разобрать",
        "Paste a valid sing-box remote-profile import link or a direct subscription URL." to "Вставьте корректную ссылку импорта remote-profile sing-box или прямой URL подписки.",
        "VPN import link" to "ссылка импорта VPN",
        "Unreadable VPN import link" to "Нечитаемая ссылка импорта VPN",
        "Unsupported provider import" to "Неподдерживаемый импорт провайдера",
        "Amnezia and other vpn:// imports are not supported. Use a normal subscription URL or add locations manually." to "Amnezia и другие импорты vpn:// не поддерживаются. Используйте обычный URL подписки или добавьте локации вручную.",
        "The import payload could not be decoded" to "Данные импорта не удалось декодировать",
        "vpn:// imports are not supported. Use a normal subscription URL or add locations manually." to "Импорты vpn:// не поддерживаются. Используйте обычный URL подписки или добавьте локации вручную.",
        "HTTP subscription URLs are not supported. Use https:// instead." to "HTTP URL подписок не поддерживаются. Используйте https://.",
        "Remote source must be an https:// URL or a supported import link" to "Удаленный источник должен быть URL https:// или поддерживаемой ссылкой импорта",
        "Remote source is empty" to "Удаленный источник пуст",
        "Remote source must be a valid https:// URL with a host." to "Удаленный источник должен быть корректным URL https:// с хостом.",
        "This sing-box import resolves to an invalid or non-HTTPS URL. Use a valid https:// URL instead." to "Этот импорт sing-box ведет к некорректному или не-HTTPS URL. Используйте корректный URL https://.",
        "Applying selected location..." to "Применение выбранной локации...",
        "Applying updated selected location..." to "Применение обновленной выбранной локации...",
        "Best location search timed out; keeping the current connection" to "Поиск лучшей локации превысил время ожидания; текущее подключение сохранено",
        "Clipboard is empty" to "Буфер обмена пуст",
        "Connection log enabled" to "Журнал подключений включен",
        "Connection log hidden" to "Журнал подключений скрыт",
        "Connection test tools enabled" to "Инструменты проверки подключения включены",
        "Connection test tools hidden" to "Инструменты проверки подключения скрыты",
        "Could not open export destination" to "Не удалось открыть место экспорта",
        "Could not open selected file" to "Не удалось открыть выбранный файл",
        "Could not open selected locations file" to "Не удалось открыть выбранный файл локаций",
        "Could not open selected rules file" to "Не удалось открыть выбранный файл правил",
        "Desktop shell: Netherlands from Whitelists" to "Нидерланды из Whitelists",
        "Desktop app initialized" to "Приложение запущено",
        "App initialized" to "Приложение запущено",
        "VPN ready on this computer" to "VPN на компьютере готов",
        "Proxy ready on this computer" to "Прокси на компьютере готов",
        "Export Locations" to "Экспорт локаций",
        "Failed to apply updated selected location" to "Не удалось применить обновленную выбранную локацию",
        "Failed to export diagnostics" to "Не удалось экспортировать диагностику",
        "Failed to export locations" to "Не удалось экспортировать локации",
        "Failed to export routing rules" to "Не удалось экспортировать правила маршрутизации",
        "Failed to find a replacement location" to "Не удалось найти заменяющую локацию",
        "Failed to import file" to "Не удалось импортировать файл",
        "Failed to open diagnostics destination" to "Не удалось открыть место сохранения диагностики",
        "Failed to save refresh settings" to "Не удалось сохранить настройки обновления",
        "Failed to update startup setting" to "Не удалось обновить настройку автозапуска",
        "Import canceled" to "Импорт отменен",
        "Invalid subscription URL" to "Некорректный URL подписки",
        "Latency history enabled" to "История задержек включена",
        "Latency history hidden" to "История задержек скрыта",
        "Live traffic stats enabled" to "Статистика трафика в реальном времени включена",
        "Live traffic stats hidden" to "Статистика трафика в реальном времени скрыта",
        "Location check cancelled" to "Проверка локации отменена",
        "Location check failed" to "Проверка локации не удалась",
        "Locations exported" to "Локации экспортированы",
        "Locations import canceled" to "Импорт локаций отменен",
        "No locations available for benchmarking" to "Нет локаций для проверки",
        "No subscriptions to refresh" to "Нет подписок для обновления",
        "No suitable location found" to "Подходящая локация не найдена",
        "Per-profile totals enabled" to "Итоги по профилям включены",
        "Per-profile totals hidden" to "Итоги по профилям скрыты",
        "Previous VPN session will be restored" to "Предыдущая VPN-сессия будет восстановлена",
        "QR scan canceled" to "Сканирование QR отменено",
        "Routing rules exported" to "Правила маршрутизации экспортированы",
        "Routing rules import canceled" to "Импорт правил маршрутизации отменен",
        "Saved routing rules" to "Правила маршрутизации сохранены",
        "Session stats enabled" to "Статистика сессии включена",
        "Session stats hidden" to "Статистика сессии скрыта",
        "Shared text is not a supported import payload" to "Отправленный текст не является поддерживаемым импортом",
        "Subscription deleted" to "Подписка удалена",
        "Subscription refresh finished, but VPN permission is required to switch in background. Previous VPN location kept as a fallback." to "Обновление подписки завершено, но для фонового переключения требуется разрешение VPN. Предыдущая VPN-локация оставлена как резервная.",
        "Subscription refresh finished. Finding the best location..." to "Обновление подписки завершено. Поиск лучшей локации...",
        "Subscription refresh finished. " to "Обновление подписки завершено. ",
        "Runtime mode: " to "Текущий режим: ",
        "Local proxy: " to "Локальный прокси: ",
        "Runtime log: " to "Журнал работы: ",
        "VPN mode preflight passed" to "Проверка режима VPN пройдена",
        "Proxy-only mode preflight passed" to "Проверка режима только прокси пройдена",
        "VPN mode preflight failed: " to "Проверка режима VPN не пройдена: ",
        "Proxy-only mode preflight failed: " to "Проверка режима только прокси не пройдена: ",
        "VPN mode unavailable: " to "Режим VPN недоступен: ",
        "Proxy-only mode unavailable: " to "Режим только прокси недоступен: ",
        "Desktop VPN capability: ready" to "VPN на компьютере: готово",
        "Desktop VPN capability: " to "VPN на компьютере: ",
        "VPN mode available" to "Режим VPN доступен",
        "Proxy mode available" to "Режим прокси доступен",
        "not ready" to "не готово",
        " check" to " проверка",
        " checks" to " проверок",
        "fail TUN device: " to "Ошибка TUN-устройства: ",
        "fail network privileges: " to "Ошибка сетевых привилегий: ",
        "fail route/DNS tooling: " to "Ошибка инструментов маршрутизации/DNS: ",
        "TUN device" to "TUN-устройство",
        "network privileges" to "сетевые привилегии",
        "route/DNS tooling" to "инструменты маршрутизации/DNS",
        "Linux TUN device is missing at /dev/net/tun. Try: sudo modprobe tun" to "Linux TUN-устройство отсутствует в /dev/net/tun. Попробуйте: sudo modprobe tun",
        "Desktop VPN mode needs CAP_NET_ADMIN. Run as root or grant sing-box capabilities: sudo setcap cap_net_admin,cap_net_raw+ep $(command -v sing-box)" to "Режиму VPN на компьютере нужен CAP_NET_ADMIN. Запустите от root или выдайте sing-box нужные права: sudo setcap cap_net_admin,cap_net_raw+ep $(command -v sing-box)",
        "Windows route/DNS tooling is unavailable. VPN mode needs netsh.exe and DNS client PowerShell cmdlets." to "Инструменты маршрутизации/DNS Windows недоступны. Режиму VPN нужны netsh.exe и команды PowerShell для DNS Client.",
    ),
    AppLanguage.GERMAN to listOf(
        "Subscription URL" to "Abo-URL",
        "Unreadable subscription URL" to "Unlesbare Abo-URL",
        "Insecure HTTP subscriptions are not supported" to "Unsichere HTTP-Abos werden nicht unterstützt",
        "Use an https:// subscription URL." to "Verwenden Sie eine https://-Abo-URL.",
        "The URL must include a valid HTTPS host" to "Die URL muss einen gültigen HTTPS-Host enthalten",
        "Paste a valid https:// subscription URL." to "Fügen Sie eine gültige https://-Abo-URL ein.",
        "Direct remote source" to "Direkte entfernte Quelle",
        "sing-box import link" to "sing-box-Import-Link",
        "Unreadable sing-box import link" to "Unlesbarer sing-box-Import-Link",
        "Only valid HTTPS remote URLs are supported" to "Nur gültige entfernte HTTPS-URLs werden unterstützt",
        "Use a sing-box import link that resolves to a valid https:// URL." to "Verwenden Sie einen sing-box-Import-Link, der auf eine gültige https://-URL verweist.",
        "Fetches remote content from the embedded URL" to "Lädt entfernten Inhalt aus der eingebetteten URL",
        "Fetches remote content from " to "Lädt entfernten Inhalt von ",
        "The import link could not be parsed" to "Der Import-Link konnte nicht gelesen werden",
        "Paste a valid sing-box remote-profile import link or a direct subscription URL." to "Fügen Sie einen gültigen sing-box remote-profile Import-Link oder eine direkte Abo-URL ein.",
        "VPN import link" to "VPN-Import-Link",
        "Unreadable VPN import link" to "Unlesbarer VPN-Import-Link",
        "Unsupported provider import" to "Nicht unterstützter Anbieter-Import",
        "Amnezia and other vpn:// imports are not supported. Use a normal subscription URL or add locations manually." to "Amnezia und andere vpn://-Importe werden nicht unterstützt. Verwenden Sie eine normale Abo-URL oder fügen Sie Standorte manuell hinzu.",
        "The import payload could not be decoded" to "Die Importdaten konnten nicht dekodiert werden",
        "vpn:// imports are not supported. Use a normal subscription URL or add locations manually." to "vpn://-Importe werden nicht unterstützt. Verwenden Sie eine normale Abo-URL oder fügen Sie Standorte manuell hinzu.",
        "HTTP subscription URLs are not supported. Use https:// instead." to "HTTP-Abo-URLs werden nicht unterstützt. Verwenden Sie stattdessen https://.",
        "Remote source must be an https:// URL or a supported import link" to "Die entfernte Quelle muss eine https://-URL oder ein unterstützter Import-Link sein",
        "Remote source is empty" to "Die entfernte Quelle ist leer",
        "Remote source must be a valid https:// URL with a host." to "Die entfernte Quelle muss eine gültige https://-URL mit Host sein.",
        "This sing-box import resolves to an invalid or non-HTTPS URL. Use a valid https:// URL instead." to "Dieser sing-box-Import verweist auf eine ungültige oder nicht-HTTPS-URL. Verwenden Sie stattdessen eine gültige https://-URL.",
        "Applying selected location..." to "Ausgewählter Standort wird angewendet...",
        "Applying updated selected location..." to "Aktualisierter ausgewählter Standort wird angewendet...",
        "Best location search timed out; keeping the current connection" to "Suche nach bestem Standort hat das Zeitlimit erreicht; aktuelle Verbindung bleibt aktiv",
        "Clipboard is empty" to "Zwischenablage ist leer",
        "Connection log enabled" to "Verbindungsprotokoll aktiviert",
        "Connection log hidden" to "Verbindungsprotokoll ausgeblendet",
        "Connection test tools enabled" to "Verbindungstest-Werkzeuge aktiviert",
        "Connection test tools hidden" to "Verbindungstest-Werkzeuge ausgeblendet",
        "Could not open export destination" to "Exportziel konnte nicht geöffnet werden",
        "Could not open selected file" to "Ausgewählte Datei konnte nicht geöffnet werden",
        "Could not open selected locations file" to "Ausgewählte Standortdatei konnte nicht geöffnet werden",
        "Could not open selected rules file" to "Ausgewählte Regeldatei konnte nicht geöffnet werden",
        "Desktop shell: Netherlands from Whitelists" to "Niederlande aus Whitelists",
        "Desktop app initialized" to "App gestartet",
        "App initialized" to "App gestartet",
        "Export Locations" to "Standorte exportieren",
        "Failed to apply updated selected location" to "Aktualisierter ausgewählter Standort konnte nicht angewendet werden",
        "Failed to export diagnostics" to "Diagnose konnte nicht exportiert werden",
        "Failed to export locations" to "Standorte konnten nicht exportiert werden",
        "Failed to export routing rules" to "Routing-Regeln konnten nicht exportiert werden",
        "Failed to find a replacement location" to "Ersatzstandort konnte nicht gefunden werden",
        "Failed to import file" to "Datei konnte nicht importiert werden",
        "Failed to open diagnostics destination" to "Diagnoseziel konnte nicht geöffnet werden",
        "Failed to save refresh settings" to "Aktualisierungseinstellungen konnten nicht gespeichert werden",
        "Failed to update startup setting" to "Startoption konnte nicht aktualisiert werden",
        "Import canceled" to "Import abgebrochen",
        "Invalid subscription URL" to "Ungültige Abo-URL",
        "Latency history enabled" to "Latenzverlauf aktiviert",
        "Latency history hidden" to "Latenzverlauf ausgeblendet",
        "Live traffic stats enabled" to "Echtzeit-Datenverkehrsstatistik aktiviert",
        "Live traffic stats hidden" to "Echtzeit-Datenverkehrsstatistik ausgeblendet",
        "Location check cancelled" to "Standortprüfung abgebrochen",
        "Location check failed" to "Standortprüfung fehlgeschlagen",
        "Locations exported" to "Standorte exportiert",
        "Locations import canceled" to "Standortimport abgebrochen",
        "No locations available for benchmarking" to "Keine Standorte für den Test verfügbar",
        "No subscriptions to refresh" to "Keine Abos zum Aktualisieren",
        "No suitable location found" to "Kein geeigneter Standort gefunden",
        "Per-profile totals enabled" to "Summen pro Profil aktiviert",
        "Per-profile totals hidden" to "Summen pro Profil ausgeblendet",
        "Previous VPN session will be restored" to "Vorherige VPN-Sitzung wird wiederhergestellt",
        "QR scan canceled" to "QR-Scan abgebrochen",
        "Routing rules exported" to "Routing-Regeln exportiert",
        "Routing rules import canceled" to "Import der Routing-Regeln abgebrochen",
        "Saved routing rules" to "Routing-Regeln gespeichert",
        "Session stats enabled" to "Sitzungsstatistik aktiviert",
        "Session stats hidden" to "Sitzungsstatistik ausgeblendet",
        "Shared text is not a supported import payload" to "Geteilter Text ist kein unterstützter Importinhalt",
        "Subscription deleted" to "Abo gelöscht",
        "Subscription refresh finished, but VPN permission is required to switch in background. Previous VPN location kept as a fallback." to "Abo-Aktualisierung abgeschlossen, aber zum Wechseln im Hintergrund ist eine VPN-Berechtigung erforderlich. Vorheriger VPN-Standort bleibt als Fallback erhalten.",
        "Subscription refresh finished. Finding the best location..." to "Abo-Aktualisierung abgeschlossen. Bester Standort wird gesucht...",
        "Subscription refresh finished. " to "Abo-Aktualisierung abgeschlossen. ",
        "Runtime mode: " to "Aktiver Modus: ",
        "Local proxy: " to "Lokaler Proxy: ",
        "Runtime log: " to "Protokolldatei: ",
        "VPN mode preflight passed" to "Prüfung für VPN-Modus bestanden",
        "Proxy-only mode preflight passed" to "Prüfung für Nur-Proxy-Modus bestanden",
        "VPN mode preflight failed: " to "Prüfung für VPN-Modus fehlgeschlagen: ",
        "Proxy-only mode preflight failed: " to "Prüfung für Nur-Proxy-Modus fehlgeschlagen: ",
        "VPN mode unavailable: " to "VPN-Modus nicht verfügbar: ",
        "Proxy-only mode unavailable: " to "Nur-Proxy-Modus nicht verfügbar: ",
        "Desktop VPN capability: ready" to "VPN auf diesem Computer: bereit",
        "Desktop VPN capability: " to "VPN auf diesem Computer: ",
        "VPN mode available" to "VPN-Modus verfügbar",
        "Proxy mode available" to "Proxy-Modus verfügbar",
        "not ready" to "nicht bereit",
        " checks" to " Prüfungen",
        " check" to " Prüfung",
        "fail TUN device: " to "Fehler TUN-Gerät: ",
        "fail network privileges: " to "Fehler Netzwerkrechte: ",
        "fail route/DNS tooling: " to "Fehler Routing-/DNS-Werkzeuge: ",
        "TUN device" to "TUN-Gerät",
        "network privileges" to "Netzwerkrechte",
        "route/DNS tooling" to "Routing-/DNS-Werkzeuge",
        "Linux TUN device is missing at /dev/net/tun. Try: sudo modprobe tun" to "Linux-TUN-Gerät fehlt unter /dev/net/tun. Versuchen Sie: sudo modprobe tun",
        "Desktop VPN mode needs CAP_NET_ADMIN. Run as root or grant sing-box capabilities: sudo setcap cap_net_admin,cap_net_raw+ep $(command -v sing-box)" to "Desktop-VPN-Modus benötigt CAP_NET_ADMIN. Als root starten oder sing-box-Berechtigungen setzen: sudo setcap cap_net_admin,cap_net_raw+ep $(command -v sing-box)",
        "Windows route/DNS tooling is unavailable. VPN mode needs netsh.exe and DNS client PowerShell cmdlets." to "Windows-Routing-/DNS-Werkzeuge sind nicht verfügbar. VPN-Modus benötigt netsh.exe und DNS-Client-PowerShell-Cmdlets.",
    ),
    AppLanguage.CHINESE to listOf(
        "Subscription URL" to "订阅 URL",
        "Unreadable subscription URL" to "无法读取的订阅 URL",
        "Insecure HTTP subscriptions are not supported" to "不支持不安全的 HTTP 订阅",
        "Use an https:// subscription URL." to "请使用 https:// 订阅 URL。",
        "The URL must include a valid HTTPS host" to "URL 必须包含有效的 HTTPS 主机",
        "Paste a valid https:// subscription URL." to "请粘贴有效的 https:// 订阅 URL。",
        "Direct remote source" to "直接远程来源",
        "sing-box import link" to "sing-box 导入链接",
        "Unreadable sing-box import link" to "无法读取的 sing-box 导入链接",
        "Only valid HTTPS remote URLs are supported" to "仅支持有效的 HTTPS 远程 URL",
        "Use a sing-box import link that resolves to a valid https:// URL." to "请使用解析到有效 https:// URL 的 sing-box 导入链接。",
        "Fetches remote content from the embedded URL" to "从嵌入 URL 获取远程内容",
        "Fetches remote content from " to "从以下位置获取远程内容：",
        "The import link could not be parsed" to "无法解析导入链接",
        "Paste a valid sing-box remote-profile import link or a direct subscription URL." to "请粘贴有效的 sing-box remote-profile 导入链接或直接订阅 URL。",
        "VPN import link" to "VPN 导入链接",
        "Unreadable VPN import link" to "无法读取的 VPN 导入链接",
        "Unsupported provider import" to "不支持的提供商导入",
        "Amnezia and other vpn:// imports are not supported. Use a normal subscription URL or add locations manually." to "不支持 Amnezia 和其他 vpn:// 导入。请使用普通订阅 URL 或手动添加节点。",
        "The import payload could not be decoded" to "无法解码导入内容",
        "vpn:// imports are not supported. Use a normal subscription URL or add locations manually." to "不支持 vpn:// 导入。请使用普通订阅 URL 或手动添加节点。",
        "HTTP subscription URLs are not supported. Use https:// instead." to "不支持 HTTP 订阅 URL。请改用 https://。",
        "Remote source must be an https:// URL or a supported import link" to "远程来源必须是 https:// URL 或支持的导入链接",
        "Remote source is empty" to "远程来源为空",
        "Remote source must be a valid https:// URL with a host." to "远程来源必须是带主机的有效 https:// URL。",
        "This sing-box import resolves to an invalid or non-HTTPS URL. Use a valid https:// URL instead." to "此 sing-box 导入解析为无效或非 HTTPS URL。请改用有效的 https:// URL。",
        "Applying selected location..." to "正在应用所选节点...",
        "Applying updated selected location..." to "正在应用更新后的所选节点...",
        "Best location search timed out; keeping the current connection" to "最佳节点搜索超时；保持当前连接",
        "Clipboard is empty" to "剪贴板为空",
        "Connection log enabled" to "连接日志已启用",
        "Connection log hidden" to "连接日志已隐藏",
        "Connection test tools enabled" to "连接测试工具已启用",
        "Connection test tools hidden" to "连接测试工具已隐藏",
        "Could not open export destination" to "无法打开导出位置",
        "Could not open selected file" to "无法打开所选文件",
        "Could not open selected locations file" to "无法打开所选节点文件",
        "Could not open selected rules file" to "无法打开所选规则文件",
        "Desktop shell: Netherlands from Whitelists" to "Whitelists 中的荷兰",
        "Desktop app initialized" to "应用已启动",
        "App initialized" to "应用已启动",
        "Export Locations" to "导出节点",
        "Failed to apply updated selected location" to "应用更新后的所选节点失败",
        "Failed to export diagnostics" to "导出诊断失败",
        "Failed to export locations" to "导出节点失败",
        "Failed to export routing rules" to "导出路由规则失败",
        "Failed to find a replacement location" to "未能找到替代节点",
        "Failed to import file" to "导入文件失败",
        "Failed to open diagnostics destination" to "无法打开诊断导出位置",
        "Failed to save refresh settings" to "保存刷新设置失败",
        "Failed to update startup setting" to "更新开机启动设置失败",
        "Import canceled" to "导入已取消",
        "Invalid subscription URL" to "订阅 URL 无效",
        "Latency history enabled" to "延迟历史已启用",
        "Latency history hidden" to "延迟历史已隐藏",
        "Live traffic stats enabled" to "实时流量统计已启用",
        "Live traffic stats hidden" to "实时流量统计已隐藏",
        "Location check cancelled" to "节点检查已取消",
        "Location check failed" to "节点检查失败",
        "Locations exported" to "节点已导出",
        "Locations import canceled" to "节点导入已取消",
        "No locations available for benchmarking" to "没有可用于测试的节点",
        "No subscriptions to refresh" to "没有可刷新的订阅",
        "No suitable location found" to "未找到合适的节点",
        "Per-profile totals enabled" to "按配置统计已启用",
        "Per-profile totals hidden" to "按配置统计已隐藏",
        "Previous VPN session will be restored" to "将恢复上一次 VPN 会话",
        "QR scan canceled" to "二维码扫描已取消",
        "Routing rules exported" to "路由规则已导出",
        "Routing rules import canceled" to "路由规则导入已取消",
        "Saved routing rules" to "路由规则已保存",
        "Session stats enabled" to "会话统计已启用",
        "Session stats hidden" to "会话统计已隐藏",
        "Shared text is not a supported import payload" to "分享的文本不是支持的导入内容",
        "Subscription deleted" to "订阅已删除",
        "Subscription refresh finished, but VPN permission is required to switch in background. Previous VPN location kept as a fallback." to "订阅刷新已完成，但后台切换需要 VPN 权限。已保留之前的 VPN 节点作为备用。",
        "Subscription refresh finished. Finding the best location..." to "订阅刷新已完成。正在寻找最佳节点...",
        "Subscription refresh finished. " to "订阅刷新已完成。",
        "Runtime mode: " to "运行模式：",
        "Local proxy: " to "本地代理：",
        "Runtime log: " to "运行日志：",
        "VPN mode preflight passed" to "VPN 模式检查已通过",
        "Proxy-only mode preflight passed" to "仅代理模式检查已通过",
        "VPN mode preflight failed: " to "VPN 模式检查失败：",
        "Proxy-only mode preflight failed: " to "仅代理模式检查失败：",
        "VPN mode unavailable: " to "VPN 模式不可用：",
        "Proxy-only mode unavailable: " to "仅代理模式不可用：",
        "Desktop VPN capability: ready" to "这台电脑上的 VPN：就绪",
        "Desktop VPN capability: " to "这台电脑上的 VPN：",
        "VPN mode available" to "VPN 模式可用",
        "Proxy mode available" to "代理模式可用",
        "not ready" to "未就绪",
        " checks" to " 项检查",
        " check" to " 项检查",
        "fail TUN device: " to "TUN 设备失败：",
        "fail network privileges: " to "网络权限失败：",
        "fail route/DNS tooling: " to "路由/DNS 工具失败：",
        "TUN device" to "TUN 设备",
        "network privileges" to "网络权限",
        "route/DNS tooling" to "路由/DNS 工具",
        "Linux TUN device is missing at /dev/net/tun. Try: sudo modprobe tun" to "Linux TUN 设备缺失于 /dev/net/tun。请尝试：sudo modprobe tun",
        "Desktop VPN mode needs CAP_NET_ADMIN. Run as root or grant sing-box capabilities: sudo setcap cap_net_admin,cap_net_raw+ep $(command -v sing-box)" to "桌面 VPN 模式需要 CAP_NET_ADMIN。请以 root 运行或授予 sing-box 权限：sudo setcap cap_net_admin,cap_net_raw+ep $(command -v sing-box)",
        "Windows route/DNS tooling is unavailable. VPN mode needs netsh.exe and DNS client PowerShell cmdlets." to "Windows 路由/DNS 工具不可用。VPN 模式需要 netsh.exe 和 DNS client PowerShell cmdlets。",
    ),
    AppLanguage.SPANISH to listOf(
        "Subscription URL" to "URL de suscripción",
        "Unreadable subscription URL" to "URL de suscripción ilegible",
        "Insecure HTTP subscriptions are not supported" to "Las suscripciones HTTP inseguras no son compatibles",
        "Use an https:// subscription URL." to "Usa una URL de suscripción https://.",
        "The URL must include a valid HTTPS host" to "La URL debe incluir un host HTTPS válido",
        "Paste a valid https:// subscription URL." to "Pega una URL de suscripción https:// válida.",
        "Direct remote source" to "Fuente remota directa",
        "sing-box import link" to "enlace de importación sing-box",
        "Unreadable sing-box import link" to "Enlace de importación sing-box ilegible",
        "Only valid HTTPS remote URLs are supported" to "Solo se admiten URL remotas HTTPS válidas",
        "Use a sing-box import link that resolves to a valid https:// URL." to "Usa un enlace de importación sing-box que resuelva a una URL https:// válida.",
        "Fetches remote content from the embedded URL" to "Obtiene contenido remoto desde la URL integrada",
        "Fetches remote content from " to "Obtiene contenido remoto de ",
        "The import link could not be parsed" to "No se pudo analizar el enlace de importación",
        "Paste a valid sing-box remote-profile import link or a direct subscription URL." to "Pega un enlace de importación remote-profile de sing-box válido o una URL directa de suscripción.",
        "VPN import link" to "enlace de importación VPN",
        "Unreadable VPN import link" to "Enlace de importación VPN ilegible",
        "Unsupported provider import" to "Importación de proveedor no compatible",
        "Amnezia and other vpn:// imports are not supported. Use a normal subscription URL or add locations manually." to "Amnezia y otras importaciones vpn:// no son compatibles. Usa una URL normal de suscripción o añade ubicaciones manualmente.",
        "The import payload could not be decoded" to "No se pudo decodificar el contenido de importación",
        "vpn:// imports are not supported. Use a normal subscription URL or add locations manually." to "Las importaciones vpn:// no son compatibles. Usa una URL normal de suscripción o añade ubicaciones manualmente.",
        "HTTP subscription URLs are not supported. Use https:// instead." to "Las URL de suscripción HTTP no son compatibles. Usa https:// en su lugar.",
        "Remote source must be an https:// URL or a supported import link" to "La fuente remota debe ser una URL https:// o un enlace de importación compatible",
        "Remote source is empty" to "La fuente remota está vacía",
        "Remote source must be a valid https:// URL with a host." to "La fuente remota debe ser una URL https:// válida con host.",
        "This sing-box import resolves to an invalid or non-HTTPS URL. Use a valid https:// URL instead." to "Esta importación de sing-box resuelve a una URL inválida o no HTTPS. Usa una URL https:// válida.",
        "Applying selected location..." to "Aplicando la ubicación seleccionada...",
        "Applying updated selected location..." to "Aplicando la ubicación seleccionada actualizada...",
        "Best location search timed out; keeping the current connection" to "La búsqueda de la mejor ubicación agotó el tiempo; se mantiene la conexión actual",
        "Clipboard is empty" to "El portapapeles está vacío",
        "Connection log enabled" to "Registro de conexión activado",
        "Connection log hidden" to "Registro de conexión oculto",
        "Connection test tools enabled" to "Herramientas de prueba de conexión activadas",
        "Connection test tools hidden" to "Herramientas de prueba de conexión ocultas",
        "Could not open export destination" to "No se pudo abrir el destino de exportación",
        "Could not open selected file" to "No se pudo abrir el archivo seleccionado",
        "Could not open selected locations file" to "No se pudo abrir el archivo de ubicaciones seleccionado",
        "Could not open selected rules file" to "No se pudo abrir el archivo de reglas seleccionado",
        "Desktop shell: Netherlands from Whitelists" to "Países Bajos desde Whitelists",
        "Desktop app initialized" to "App iniciada",
        "App initialized" to "App iniciada",
        "Export Locations" to "Exportar ubicaciones",
        "Failed to apply updated selected location" to "No se pudo aplicar la ubicación seleccionada actualizada",
        "Failed to export diagnostics" to "No se pudieron exportar los diagnósticos",
        "Failed to export locations" to "No se pudieron exportar las ubicaciones",
        "Failed to export routing rules" to "No se pudieron exportar las reglas de enrutamiento",
        "Failed to find a replacement location" to "No se pudo encontrar una ubicación de reemplazo",
        "Failed to import file" to "No se pudo importar el archivo",
        "Failed to open diagnostics destination" to "No se pudo abrir el destino de diagnósticos",
        "Failed to save refresh settings" to "No se pudieron guardar los ajustes de actualización",
        "Failed to update startup setting" to "No se pudo actualizar el ajuste de inicio",
        "Import canceled" to "Importación cancelada",
        "Invalid subscription URL" to "URL de suscripción inválida",
        "Latency history enabled" to "Historial de latencia activado",
        "Latency history hidden" to "Historial de latencia oculto",
        "Live traffic stats enabled" to "Estadísticas de tráfico en vivo activadas",
        "Live traffic stats hidden" to "Estadísticas de tráfico en vivo ocultas",
        "Location check cancelled" to "Comprobación de ubicación cancelada",
        "Location check failed" to "Comprobación de ubicación fallida",
        "Locations exported" to "Ubicaciones exportadas",
        "Locations import canceled" to "Importación de ubicaciones cancelada",
        "No locations available for benchmarking" to "No hay ubicaciones disponibles para probar",
        "No subscriptions to refresh" to "No hay suscripciones para actualizar",
        "No suitable location found" to "No se encontró una ubicación adecuada",
        "Per-profile totals enabled" to "Totales por perfil activados",
        "Per-profile totals hidden" to "Totales por perfil ocultos",
        "Previous VPN session will be restored" to "Se restaurará la sesión VPN anterior",
        "QR scan canceled" to "Escaneo QR cancelado",
        "Routing rules exported" to "Reglas de enrutamiento exportadas",
        "Routing rules import canceled" to "Importación de reglas de enrutamiento cancelada",
        "Saved routing rules" to "Reglas de enrutamiento guardadas",
        "Session stats enabled" to "Estadísticas de sesión activadas",
        "Session stats hidden" to "Estadísticas de sesión ocultas",
        "Shared text is not a supported import payload" to "El texto compartido no es un contenido de importación compatible",
        "Subscription deleted" to "Suscripción eliminada",
        "Subscription refresh finished, but VPN permission is required to switch in background. Previous VPN location kept as a fallback." to "La actualización de la suscripción terminó, pero se requiere permiso de VPN para cambiar en segundo plano. La ubicación VPN anterior se conserva como respaldo.",
        "Subscription refresh finished. Finding the best location..." to "La actualización de la suscripción terminó. Buscando la mejor ubicación...",
        "Subscription refresh finished. " to "La actualización de la suscripción terminó. ",
        "Runtime mode: " to "Modo actual: ",
        "Local proxy: " to "Proxy local: ",
        "Runtime log: " to "Registro de actividad: ",
        "VPN mode preflight passed" to "Comprobación del modo VPN superada",
        "Proxy-only mode preflight passed" to "Comprobación del modo solo proxy superada",
        "VPN mode preflight failed: " to "Comprobación del modo VPN fallida: ",
        "Proxy-only mode preflight failed: " to "Comprobación del modo solo proxy fallida: ",
        "VPN mode unavailable: " to "Modo VPN no disponible: ",
        "Proxy-only mode unavailable: " to "Modo solo proxy no disponible: ",
        "Desktop VPN capability: ready" to "VPN en este equipo: lista",
        "Desktop VPN capability: " to "VPN en este equipo: ",
        "VPN mode available" to "Modo VPN disponible",
        "Proxy mode available" to "Modo proxy disponible",
        "not ready" to "no listo",
        " checks" to " comprobaciones",
        " check" to " comprobación",
        "fail TUN device: " to "Error de dispositivo TUN: ",
        "fail network privileges: " to "Error de privilegios de red: ",
        "fail route/DNS tooling: " to "Error de herramientas de ruta/DNS: ",
        "TUN device" to "dispositivo TUN",
        "network privileges" to "privilegios de red",
        "route/DNS tooling" to "herramientas de ruta/DNS",
        "Linux TUN device is missing at /dev/net/tun. Try: sudo modprobe tun" to "Falta el dispositivo TUN de Linux en /dev/net/tun. Prueba: sudo modprobe tun",
        "Desktop VPN mode needs CAP_NET_ADMIN. Run as root or grant sing-box capabilities: sudo setcap cap_net_admin,cap_net_raw+ep $(command -v sing-box)" to "El modo VPN en este equipo necesita CAP_NET_ADMIN. Ejecuta como root o concede permisos a sing-box: sudo setcap cap_net_admin,cap_net_raw+ep $(command -v sing-box)",
        "Windows route/DNS tooling is unavailable. VPN mode needs netsh.exe and DNS client PowerShell cmdlets." to "Las herramientas de ruta/DNS de Windows no están disponibles. El modo VPN necesita netsh.exe y cmdlets de DNS client PowerShell.",
    ),
    AppLanguage.PORTUGUESE to listOf(
        "Subscription URL" to "URL da assinatura",
        "Unreadable subscription URL" to "URL da assinatura ilegível",
        "Insecure HTTP subscriptions are not supported" to "Assinaturas HTTP inseguras não são suportadas",
        "Use an https:// subscription URL." to "Use uma URL de assinatura https://.",
        "The URL must include a valid HTTPS host" to "A URL deve incluir um host HTTPS válido",
        "Paste a valid https:// subscription URL." to "Cole uma URL de assinatura https:// válida.",
        "Direct remote source" to "Fonte remota direta",
        "sing-box import link" to "link de importação sing-box",
        "Unreadable sing-box import link" to "Link de importação sing-box ilegível",
        "Only valid HTTPS remote URLs are supported" to "Apenas URLs remotas HTTPS válidas são suportadas",
        "Use a sing-box import link that resolves to a valid https:// URL." to "Use um link de importação sing-box que resolva para uma URL https:// válida.",
        "Fetches remote content from the embedded URL" to "Busca conteúdo remoto da URL incorporada",
        "Fetches remote content from " to "Busca conteúdo remoto de ",
        "The import link could not be parsed" to "Não foi possível interpretar o link de importação",
        "Paste a valid sing-box remote-profile import link or a direct subscription URL." to "Cole um link de importação remote-profile do sing-box válido ou uma URL direta de assinatura.",
        "VPN import link" to "link de importação VPN",
        "Unreadable VPN import link" to "Link de importação VPN ilegível",
        "Unsupported provider import" to "Importação de provedor não suportada",
        "Amnezia and other vpn:// imports are not supported. Use a normal subscription URL or add locations manually." to "Amnezia e outras importações vpn:// não são suportadas. Use uma URL normal de assinatura ou adicione localizações manualmente.",
        "The import payload could not be decoded" to "Não foi possível decodificar os dados de importação",
        "vpn:// imports are not supported. Use a normal subscription URL or add locations manually." to "Importações vpn:// não são suportadas. Use uma URL normal de assinatura ou adicione localizações manualmente.",
        "HTTP subscription URLs are not supported. Use https:// instead." to "URLs de assinatura HTTP não são suportadas. Use https://.",
        "Remote source must be an https:// URL or a supported import link" to "A fonte remota deve ser uma URL https:// ou um link de importação suportado",
        "Remote source is empty" to "A fonte remota está vazia",
        "Remote source must be a valid https:// URL with a host." to "A fonte remota deve ser uma URL https:// válida com host.",
        "This sing-box import resolves to an invalid or non-HTTPS URL. Use a valid https:// URL instead." to "Esta importação do sing-box resolve para uma URL inválida ou não HTTPS. Use uma URL https:// válida.",
        "Applying selected location..." to "Aplicando a localização selecionada...",
        "Applying updated selected location..." to "Aplicando a localização selecionada atualizada...",
        "Best location search timed out; keeping the current connection" to "A busca pela melhor localização expirou; mantendo a conexão atual",
        "Clipboard is empty" to "A área de transferência está vazia",
        "Connection log enabled" to "Registro de conexão ativado",
        "Connection log hidden" to "Registro de conexão oculto",
        "Connection test tools enabled" to "Ferramentas de teste de conexão ativadas",
        "Connection test tools hidden" to "Ferramentas de teste de conexão ocultas",
        "Could not open export destination" to "Não foi possível abrir o destino de exportação",
        "Could not open selected file" to "Não foi possível abrir o arquivo selecionado",
        "Could not open selected locations file" to "Não foi possível abrir o arquivo de localizações selecionado",
        "Could not open selected rules file" to "Não foi possível abrir o arquivo de regras selecionado",
        "Desktop shell: Netherlands from Whitelists" to "Países Baixos de Whitelists",
        "Desktop app initialized" to "App iniciada",
        "App initialized" to "App iniciada",
        "Export Locations" to "Exportar localizações",
        "Failed to apply updated selected location" to "Falha ao aplicar a localização selecionada atualizada",
        "Failed to export diagnostics" to "Falha ao exportar diagnósticos",
        "Failed to export locations" to "Falha ao exportar localizações",
        "Failed to export routing rules" to "Falha ao exportar regras de roteamento",
        "Failed to find a replacement location" to "Falha ao encontrar uma localização substituta",
        "Failed to import file" to "Falha ao importar arquivo",
        "Failed to open diagnostics destination" to "Falha ao abrir o destino de diagnósticos",
        "Failed to save refresh settings" to "Falha ao salvar as configurações de atualização",
        "Failed to update startup setting" to "Falha ao atualizar a configuração de inicialização",
        "Import canceled" to "Importação cancelada",
        "Invalid subscription URL" to "URL da assinatura inválida",
        "Latency history enabled" to "Histórico de latência ativado",
        "Latency history hidden" to "Histórico de latência oculto",
        "Live traffic stats enabled" to "Estatísticas de tráfego ao vivo ativadas",
        "Live traffic stats hidden" to "Estatísticas de tráfego ao vivo ocultas",
        "Location check cancelled" to "Verificação de localização cancelada",
        "Location check failed" to "Verificação de localização falhou",
        "Locations exported" to "Localizações exportadas",
        "Locations import canceled" to "Importação de localizações cancelada",
        "No locations available for benchmarking" to "Nenhuma localização disponível para testar",
        "No subscriptions to refresh" to "Nenhuma assinatura para atualizar",
        "No suitable location found" to "Nenhuma localização adequada encontrada",
        "Per-profile totals enabled" to "Totais por perfil ativados",
        "Per-profile totals hidden" to "Totais por perfil ocultos",
        "Previous VPN session will be restored" to "A sessão VPN anterior será restaurada",
        "QR scan canceled" to "Leitura de QR cancelada",
        "Routing rules exported" to "Regras de roteamento exportadas",
        "Routing rules import canceled" to "Importação de regras de roteamento cancelada",
        "Saved routing rules" to "Regras de roteamento salvas",
        "Session stats enabled" to "Estatísticas da sessão ativadas",
        "Session stats hidden" to "Estatísticas da sessão ocultas",
        "Shared text is not a supported import payload" to "O texto compartilhado não é um conteúdo de importação suportado",
        "Subscription deleted" to "Assinatura excluída",
        "Subscription refresh finished, but VPN permission is required to switch in background. Previous VPN location kept as a fallback." to "A atualização da assinatura terminou, mas a permissão de VPN é necessária para trocar em segundo plano. A localização VPN anterior foi mantida como reserva.",
        "Subscription refresh finished. Finding the best location..." to "A atualização da assinatura terminou. Procurando a melhor localização...",
        "Subscription refresh finished. " to "A atualização da assinatura terminou. ",
        "Runtime mode: " to "Modo atual: ",
        "Local proxy: " to "Proxy local: ",
        "Runtime log: " to "Registro de atividade: ",
        "VPN mode preflight passed" to "Verificação do modo VPN aprovada",
        "Proxy-only mode preflight passed" to "Verificação do modo somente proxy aprovada",
        "VPN mode preflight failed: " to "Verificação do modo VPN falhou: ",
        "Proxy-only mode preflight failed: " to "Verificação do modo somente proxy falhou: ",
        "VPN mode unavailable: " to "Modo VPN indisponível: ",
        "Proxy-only mode unavailable: " to "Modo somente proxy indisponível: ",
        "Desktop VPN capability: ready" to "VPN neste computador: pronta",
        "Desktop VPN capability: " to "VPN neste computador: ",
        "VPN mode available" to "Modo VPN disponível",
        "Proxy mode available" to "Modo proxy disponível",
        "not ready" to "não pronto",
        " checks" to " verificações",
        " check" to " verificação",
        "fail TUN device: " to "Falha no dispositivo TUN: ",
        "fail network privileges: " to "Falha nos privilégios de rede: ",
        "fail route/DNS tooling: " to "Falha nas ferramentas de rota/DNS: ",
        "TUN device" to "dispositivo TUN",
        "network privileges" to "privilégios de rede",
        "route/DNS tooling" to "ferramentas de rota/DNS",
        "Linux TUN device is missing at /dev/net/tun. Try: sudo modprobe tun" to "O dispositivo TUN do Linux está ausente em /dev/net/tun. Tente: sudo modprobe tun",
        "Desktop VPN mode needs CAP_NET_ADMIN. Run as root or grant sing-box capabilities: sudo setcap cap_net_admin,cap_net_raw+ep $(command -v sing-box)" to "O modo VPN no computador precisa de CAP_NET_ADMIN. Execute como root ou conceda permissões ao sing-box: sudo setcap cap_net_admin,cap_net_raw+ep $(command -v sing-box)",
        "Windows route/DNS tooling is unavailable. VPN mode needs netsh.exe and DNS client PowerShell cmdlets." to "As ferramentas de rota/DNS do Windows estão indisponíveis. O modo VPN precisa de netsh.exe e cmdlets DNS client do PowerShell.",
    ),
    AppLanguage.FRENCH to listOf(
        "Subscription URL" to "URL d'abonnement",
        "Unreadable subscription URL" to "URL d'abonnement illisible",
        "Insecure HTTP subscriptions are not supported" to "Les abonnements HTTP non sécurisés ne sont pas pris en charge",
        "Use an https:// subscription URL." to "Utilisez une URL d'abonnement https://.",
        "The URL must include a valid HTTPS host" to "L'URL doit inclure un hôte HTTPS valide",
        "Paste a valid https:// subscription URL." to "Collez une URL d'abonnement https:// valide.",
        "Direct remote source" to "Source distante directe",
        "sing-box import link" to "lien d'import sing-box",
        "Unreadable sing-box import link" to "Lien d'import sing-box illisible",
        "Only valid HTTPS remote URLs are supported" to "Seules les URL distantes HTTPS valides sont prises en charge",
        "Use a sing-box import link that resolves to a valid https:// URL." to "Utilisez un lien d'import sing-box qui résout vers une URL https:// valide.",
        "Fetches remote content from the embedded URL" to "Récupère le contenu distant depuis l'URL intégrée",
        "Fetches remote content from " to "Récupère le contenu distant depuis ",
        "The import link could not be parsed" to "Le lien d'import n'a pas pu être analysé",
        "Paste a valid sing-box remote-profile import link or a direct subscription URL." to "Collez un lien d'import remote-profile sing-box valide ou une URL d'abonnement directe.",
        "VPN import link" to "lien d'import VPN",
        "Unreadable VPN import link" to "Lien d'import VPN illisible",
        "Unsupported provider import" to "Import de fournisseur non pris en charge",
        "Amnezia and other vpn:// imports are not supported. Use a normal subscription URL or add locations manually." to "Amnezia et les autres imports vpn:// ne sont pas pris en charge. Utilisez une URL d'abonnement normale ou ajoutez des emplacements manuellement.",
        "The import payload could not be decoded" to "Le contenu d'import n'a pas pu être décodé",
        "vpn:// imports are not supported. Use a normal subscription URL or add locations manually." to "Les imports vpn:// ne sont pas pris en charge. Utilisez une URL d'abonnement normale ou ajoutez des emplacements manuellement.",
        "HTTP subscription URLs are not supported. Use https:// instead." to "Les URL d'abonnement HTTP ne sont pas prises en charge. Utilisez https://.",
        "Remote source must be an https:// URL or a supported import link" to "La source distante doit être une URL https:// ou un lien d'import pris en charge",
        "Remote source is empty" to "La source distante est vide",
        "Remote source must be a valid https:// URL with a host." to "La source distante doit être une URL https:// valide avec un hôte.",
        "This sing-box import resolves to an invalid or non-HTTPS URL. Use a valid https:// URL instead." to "Cet import sing-box pointe vers une URL invalide ou non HTTPS. Utilisez une URL https:// valide.",
        "Applying selected location..." to "Application de l'emplacement sélectionné...",
        "Applying updated selected location..." to "Application de l'emplacement sélectionné mis à jour...",
        "Best location search timed out; keeping the current connection" to "La recherche du meilleur emplacement a expiré; la connexion actuelle est conservée",
        "Clipboard is empty" to "Le presse-papiers est vide",
        "Connection log enabled" to "Journal de connexion activé",
        "Connection log hidden" to "Journal de connexion masqué",
        "Connection test tools enabled" to "Outils de test de connexion activés",
        "Connection test tools hidden" to "Outils de test de connexion masqués",
        "Could not open export destination" to "Impossible d'ouvrir la destination d'export",
        "Could not open selected file" to "Impossible d'ouvrir le fichier sélectionné",
        "Could not open selected locations file" to "Impossible d'ouvrir le fichier d'emplacements sélectionné",
        "Could not open selected rules file" to "Impossible d'ouvrir le fichier de règles sélectionné",
        "Desktop shell: Netherlands from Whitelists" to "Pays-Bas depuis Whitelists",
        "Desktop app initialized" to "App démarrée",
        "App initialized" to "App démarrée",
        "Export Locations" to "Exporter les emplacements",
        "Failed to apply updated selected location" to "Impossible d'appliquer l'emplacement sélectionné mis à jour",
        "Failed to export diagnostics" to "Impossible d'exporter les diagnostics",
        "Failed to export locations" to "Impossible d'exporter les emplacements",
        "Failed to export routing rules" to "Impossible d'exporter les règles de routage",
        "Failed to find a replacement location" to "Impossible de trouver un emplacement de remplacement",
        "Failed to import file" to "Impossible d'importer le fichier",
        "Failed to open diagnostics destination" to "Impossible d'ouvrir la destination des diagnostics",
        "Failed to save refresh settings" to "Impossible d'enregistrer les paramètres d'actualisation",
        "Failed to update startup setting" to "Impossible de mettre à jour le paramètre de démarrage",
        "Import canceled" to "Import annulé",
        "Invalid subscription URL" to "URL d'abonnement invalide",
        "Latency history enabled" to "Historique de latence activé",
        "Latency history hidden" to "Historique de latence masqué",
        "Live traffic stats enabled" to "Statistiques de trafic en direct activées",
        "Live traffic stats hidden" to "Statistiques de trafic en direct masquées",
        "Location check cancelled" to "Vérification d'emplacement annulée",
        "Location check failed" to "Vérification d'emplacement échouée",
        "Locations exported" to "Emplacements exportés",
        "Locations import canceled" to "Import des emplacements annulé",
        "No locations available for benchmarking" to "Aucun emplacement disponible pour le test",
        "No subscriptions to refresh" to "Aucun abonnement à actualiser",
        "No suitable location found" to "Aucun emplacement adapté trouvé",
        "Per-profile totals enabled" to "Totaux par profil activés",
        "Per-profile totals hidden" to "Totaux par profil masqués",
        "Previous VPN session will be restored" to "La session VPN précédente sera restaurée",
        "QR scan canceled" to "Scan QR annulé",
        "Routing rules exported" to "Règles de routage exportées",
        "Routing rules import canceled" to "Import des règles de routage annulé",
        "Saved routing rules" to "Règles de routage enregistrées",
        "Session stats enabled" to "Statistiques de session activées",
        "Session stats hidden" to "Statistiques de session masquées",
        "Shared text is not a supported import payload" to "Le texte partagé n'est pas un contenu d'import pris en charge",
        "Subscription deleted" to "Abonnement supprimé",
        "Subscription refresh finished, but VPN permission is required to switch in background. Previous VPN location kept as a fallback." to "L'actualisation de l'abonnement est terminée, mais l'autorisation VPN est requise pour changer en arrière-plan. L'emplacement VPN précédent est conservé comme solution de secours.",
        "Subscription refresh finished. Finding the best location..." to "L'actualisation de l'abonnement est terminée. Recherche du meilleur emplacement...",
        "Subscription refresh finished. " to "L'actualisation de l'abonnement est terminée. ",
        "Runtime mode: " to "Mode actuel : ",
        "Local proxy: " to "Proxy local : ",
        "Runtime log: " to "Journal d'activité : ",
        "VPN mode preflight passed" to "Vérification du mode VPN réussie",
        "Proxy-only mode preflight passed" to "Vérification du mode proxy uniquement réussie",
        "VPN mode preflight failed: " to "Vérification du mode VPN échouée : ",
        "Proxy-only mode preflight failed: " to "Vérification du mode proxy uniquement échouée : ",
        "VPN mode unavailable: " to "Mode VPN indisponible : ",
        "Proxy-only mode unavailable: " to "Mode Proxy uniquement indisponible : ",
        "Desktop VPN capability: ready" to "VPN sur cet ordinateur : prêt",
        "Desktop VPN capability: " to "VPN sur cet ordinateur : ",
        "VPN mode available" to "Mode VPN disponible",
        "Proxy mode available" to "Mode proxy disponible",
        "not ready" to "pas prêt",
        " checks" to " vérifications",
        " check" to " vérification",
        "fail TUN device: " to "Échec du périphérique TUN : ",
        "fail network privileges: " to "Échec des privilèges réseau : ",
        "fail route/DNS tooling: " to "Échec des outils route/DNS : ",
        "TUN device" to "périphérique TUN",
        "network privileges" to "privilèges réseau",
        "route/DNS tooling" to "outils route/DNS",
        "Linux TUN device is missing at /dev/net/tun. Try: sudo modprobe tun" to "Le périphérique TUN Linux est absent dans /dev/net/tun. Essayez : sudo modprobe tun",
        "Desktop VPN mode needs CAP_NET_ADMIN. Run as root or grant sing-box capabilities: sudo setcap cap_net_admin,cap_net_raw+ep $(command -v sing-box)" to "Le mode VPN sur ordinateur nécessite CAP_NET_ADMIN. Lancez en root ou accordez les permissions à sing-box : sudo setcap cap_net_admin,cap_net_raw+ep $(command -v sing-box)",
        "Windows route/DNS tooling is unavailable. VPN mode needs netsh.exe and DNS client PowerShell cmdlets." to "Les outils route/DNS Windows sont indisponibles. Le mode VPN nécessite netsh.exe et les cmdlets DNS client PowerShell.",
    ),
).mapValues { (_, replacements) ->
    replacements.sortedByDescending { it.first.length }
}
