"""Direct macOS fixture evidence, not guest/package or authorization admission.

The existing rollback driver can use DurableMacBoundary after its caller admits
the guest, package pair, source, resources and visible authorization. This module
does not implement SecurityAgent input, install a package or publish acceptance.
Only public argv generated by the existing MacBoundary is accepted. Raw command
records precede its JSON parser, including failures and timeouts. A CLI timeout
never means the accepted installer job was cancelled or can be replayed.
"""
from __future__ import annotations

from dataclasses import dataclass
import hashlib
import json
import os
from pathlib import Path
import selectors
import stat
import subprocess
import sys
import time
from uuid import UUID

from scripts.integration.macos_rollback_fixture import MacBoundary, FixtureError
from scripts.macos_fixture_processes import (
    FixtureProcessObserver, ProcessIdentity, process_rows,
)

CAP = 1024 * 1024
CHUNK = 64 * 1024
TIMEOUT = 30.0
MAX_COMMANDS = 128


def _uuid(value: str) -> str:
    if type(value) is not str or str(UUID(value)) != value:
        raise FixtureError("direct_capture_identity")
    return value


def _generation(s: os.stat_result) -> tuple[int, ...]:
    return (s.st_dev, s.st_ino, s.st_mode, s.st_uid, s.st_gid,
            s.st_nlink, s.st_size, s.st_mtime_ns, s.st_ctime_ns)


def _parent_identity(s: os.stat_result) -> tuple[int, ...]:
    # Structural parent5, as used by the repository descriptor readers. Shared
    # ancestors may contain unrelated new entries; this is not full tree proof.
    return (s.st_dev, s.st_ino, s.st_mode, s.st_uid, s.st_gid)


def _encode(value: object) -> bytes:
    return (json.dumps(value, sort_keys=True, separators=(",", ":"),
                       allow_nan=False) + "\n").encode("utf-8")


@dataclass(frozen=True)
class RawRecord:
    argv: tuple[str, ...]
    stdout: bytes
    stderr: bytes
    returncode: int | None
    stdout_eof: bool
    stderr_eof: bool
    failure: str | None
    child_pid: int | None
    manifest: Path
    manifest_sha256: str


class EvidenceDirectory:
    """Hold private named directory identity; never overwrite an attempt."""

    def __init__(self, path: Path):
        path = Path(path)
        if not path.is_absolute() or path != Path(os.path.abspath(path)):
            raise FixtureError("direct_capture_path")
        self.path = path
        self.chain: list[tuple[int, Path, tuple[int, ...]]] = []
        self.leaves: list[tuple[int, str, tuple[int, ...], str]] = []
        self.fd = -1
        try:
            for parent in reversed(path.parents):
                fd = os.open(parent, os.O_RDONLY | os.O_DIRECTORY | os.O_NOFOLLOW)
                s = os.fstat(fd)
                if not stat.S_ISDIR(s.st_mode) or _parent_identity(s) != _parent_identity(os.stat(parent, follow_symlinks=False)):
                    os.close(fd)
                    raise FixtureError("direct_capture_parent")
                self.chain.append((fd, parent, _parent_identity(s)))
            self.fd = os.open(path, os.O_RDONLY | os.O_DIRECTORY | os.O_NOFOLLOW)
            s = os.fstat(self.fd)
            if s.st_uid != os.getuid() or stat.S_IMODE(s.st_mode) != 0o700:
                raise FixtureError("direct_capture_private")
            self.identity = (s.st_dev, s.st_ino, s.st_mode, s.st_uid, s.st_gid)
            if os.listdir(self.fd):
                raise FixtureError("direct_capture_evidence_not_empty")
            self.guard()
        except BaseException:
            self.close()
            raise

    def guard(self) -> None:
        for fd, parent, generation in self.chain:
            if _parent_identity(os.fstat(fd)) != generation or _parent_identity(os.stat(parent, follow_symlinks=False)) != generation:
                raise FixtureError("direct_capture_parent_changed")
        held = os.fstat(self.fd)
        named = os.stat(self.path, follow_symlinks=False)
        identity = lambda s: (s.st_dev, s.st_ino, s.st_mode, s.st_uid, s.st_gid)
        if identity(held) != self.identity or identity(named) != self.identity:
            raise FixtureError("direct_capture_directory_changed")

    def write(self, name: str, raw: bytes) -> dict[str, object]:
        if type(raw) is not bytes or len(raw) > CHUNK or not name or "/" in name or name in {".", ".."}:
            raise FixtureError("direct_capture_record")
        self.guard()
        fd = os.open(name, os.O_RDWR | os.O_CREAT | os.O_EXCL | os.O_NOFOLLOW,
                     0o600, dir_fd=self.fd)
        try:
            view = memoryview(raw)
            while view:
                n = os.write(fd, view)
                if n <= 0:
                    raise FixtureError("direct_capture_short_write")
                view = view[n:]
            os.fsync(fd)
            s = os.fstat(fd)
            if _generation(s) != _generation(os.stat(name, dir_fd=self.fd, follow_symlinks=False)):
                raise FixtureError("direct_capture_record_changed")
            record = {"name": name, "size": len(raw), "sha256": hashlib.sha256(raw).hexdigest(),
                      "generation": list(_generation(s)), "generationFormat": "descriptor9"}
            self.leaves.append((fd, name, _generation(s), record["sha256"]))
            fd = -1  # The directory owns every raw/journal FD through closing.
        finally:
            if fd >= 0:
                os.close(fd)
        os.fsync(self.fd)
        self.guard()
        return record

    def body_guard(self) -> None:
        if set(os.listdir(self.fd)) != {name for _, name, _, _ in self.leaves}:
            raise FixtureError("direct_capture_catalogue_changed")
        for fd, _, generation, digest in self.leaves:
            raw = os.pread(fd, CHUNK + 1, 0)
            if len(raw) != generation[6] or hashlib.sha256(raw).hexdigest() != digest:
                raise FixtureError("direct_capture_record_changed")

    def generation_guard(self) -> None:
        # Close directory/parents before the terminal pure leaf checks.
        self.guard()
        # No hash/catalogue/body/parent reads after the first original leaf check.
        for fd, name, generation, _ in self.leaves:
            if _generation(os.fstat(fd)) != generation or \
                    _generation(os.stat(name, dir_fd=self.fd, follow_symlinks=False)) != generation:
                raise FixtureError("direct_capture_record_changed")

    def close(self) -> None:
        for fd, _, _, _ in self.leaves:
            os.close(fd)
        self.leaves = []
        if self.fd >= 0:
            os.close(self.fd)
            self.fd = -1
        for fd, _, _ in self.chain:
            os.close(fd)
        self.chain = []


class DurableMacBoundary(MacBoundary):
    """Reuse public rollback grammar; its caller supplies all native admission.

    An instance observes exactly one admitted app/state pair. It cannot close or
    kill an installer coordinator. The bounded child is the public CLI client;
    the capture record explicitly makes no descendant/job cleanup claim.
    """

    def __init__(self, app: Path, state_dir: Path, evidence: Path, correlation: str,
                 controller_id: str):
        self.app = Path(app)
        self.state_dir = Path(state_dir)
        self.observer = FixtureProcessObserver(str(self.app / "Contents/MacOS/vpn-control"), str(self.state_dir))
        self.correlation = _uuid(correlation)
        self.controller_id = _uuid(controller_id)
        self.evidence = EvidenceDirectory(evidence)
        self.records: list[RawRecord] = []
        self.sticky_unknown = False
        self.install_submitted = False
        self.launcher_fd = -1
        self.launcher_chain: list[tuple[int, Path, tuple[int, ...]]] = []
        try:
            for parent in reversed(Path(self.observer.app).parents):
                fd = os.open(parent, os.O_RDONLY | os.O_DIRECTORY | os.O_NOFOLLOW)
                s = os.fstat(fd)
                if _parent_identity(s) != _parent_identity(os.stat(parent, follow_symlinks=False)):
                    os.close(fd)
                    raise FixtureError("direct_capture_launcher_parent")
                self.launcher_chain.append((fd, parent, _parent_identity(s)))
            self.launcher_fd = os.open(self.observer.app, os.O_RDONLY | os.O_NOFOLLOW | os.O_NONBLOCK)
            s = os.fstat(self.launcher_fd)
            if not stat.S_ISREG(s.st_mode) or not s.st_mode & 0o111 or s.st_nlink != 1:
                raise FixtureError("direct_capture_launcher")
            self.launcher_generation = _generation(s)
            self.launcher_sha256 = self._launcher_hash()
            self._launcher_guard()
        except BaseException:
            self.close()
            raise

    def _launcher_hash(self) -> str:
        digest = hashlib.sha256()
        offset = 0
        while raw := os.pread(self.launcher_fd, CHUNK, offset):
            digest.update(raw)
            offset += len(raw)
            if offset > 64 * CAP:
                raise FixtureError("direct_capture_launcher_cap")
        return digest.hexdigest()

    def _launcher_guard(self) -> None:
        if self._launcher_hash() != self.launcher_sha256:
            raise FixtureError("direct_capture_launcher_changed")
        for fd, parent, generation in self.launcher_chain:
            if _parent_identity(os.fstat(fd)) != generation or _parent_identity(os.stat(parent, follow_symlinks=False)) != generation:
                raise FixtureError("direct_capture_launcher_parent_changed")
        self.evidence.guard()
        self._launcher_generation_guard()

    def _launcher_generation_guard(self) -> None:
        # All hash/parent/directory reads precede the final launcher leaf close.
        if _generation(os.fstat(self.launcher_fd)) != self.launcher_generation or \
                _generation(os.stat(self.observer.app, follow_symlinks=False)) != self.launcher_generation:
            raise FixtureError("direct_capture_launcher_changed")

    def _command(self, argv: list[str]) -> str:
        prefix = [self.observer.app, "--state-dir", self.observer.state_dir, "--json"]
        if type(argv) is not list or any(type(x) is not str for x in argv) or argv[:4] != prefix:
            raise FixtureError("direct_capture_public_scope")
        tail = argv[4:]
        if tail in (["status"], ["updates", "status"], ["updates", "check"], ["updates", "download"]):
            if self.sticky_unknown and tail in (["updates", "check"], ["updates", "download"]):
                raise FixtureError("direct_capture_unknown_effect")
            return "-".join(tail)
        if len(tail) >= 3 and tail[0] == "--controller-id":
            _uuid(tail[1])
            if tail[1] != self.controller_id:
                raise FixtureError("direct_capture_controller_changed")
            if tail[2:] == ["--async", "updates", "install"]:
                if self.sticky_unknown or self.install_submitted:
                    raise FixtureError("direct_capture_install_no_replay")
                return "install"
            if len(tail) == 5 and tail[2:4] == ["operations", "status"]:
                _uuid(tail[4])
                return "operation-status"
        raise FixtureError("direct_capture_public_scope")

    def _capture(self, argv: list[str]) -> RawRecord:
        self._command(argv)
        self.capture_partial = None
        self.capture_cleanup_failed = False
        try:
            return self._capture_record(argv)
        except BaseException:
            # Journal/guard failures anywhere after the fence must not renew
            # effect authority. Preserve the primary exception unchanged.
            self.sticky_unknown = True
            try:
                partial = self.capture_partial
                parts = {}
                if partial is not None:
                    for stream in ("stdout", "stderr"):
                        parts[stream] = [self.evidence.write(
                            f"{len(self.records):04d}-failure-{stream}-{offset // CHUNK:04d}.raw",
                            partial[stream][offset:offset + CHUNK])
                            for offset in range(0, len(partial[stream]), CHUNK)]
                self.evidence.write(f"{len(self.records):04d}-capture-unknown.json", _encode({
                    "schema": 1, "correlationId": self.correlation,
                    "failure": "capture-or-journal-unknown", "parts": parts,
                    "cleanupFailed": self.capture_cleanup_failed,
                    "jobReplayAllowed": False, "nativeAcceptanceGranted": False}))
            except BaseException:
                pass  # An unavailable evidence directory cannot be repaired here.
            raise

    def _capture_record(self, argv: list[str]) -> RawRecord:
        role = self._command(argv)
        if len(self.records) >= MAX_COMMANDS:
            self.sticky_unknown = True
            raise FixtureError("direct_capture_command_cap")
        self._launcher_guard()
        index = len(self.records)
        stem = f"{index:04d}-{role}"
        self.evidence.write(stem + "-intent.json", _encode({"schema": 1, "correlationId": self.correlation,
            "argv": argv, "role": role, "jobReplayAllowed": False, "nativeAdmissionGranted": False}))
        # Exclusive intent is the dispatch fence; failed spawn cannot be replayed.
        if role == "install":
            self.install_submitted = True
        output = {"stdout": bytearray(), "stderr": bytearray()}
        eof = {"stdout": False, "stderr": False}
        parts: dict[str, list[dict[str, object]]] = {"stdout": [], "stderr": []}
        committed = {"stdout": 0, "stderr": 0}
        failure = None
        process = None
        rc = None
        deadline = time.monotonic() + TIMEOUT
        try:
            # The durable intent write can take time or expose source drift.
            # Close original held/named launcher and structural parent pins
            # again at the actual release boundary, not only before journaling.
            self.evidence.body_guard()
            self._launcher_guard()
            self.evidence.generation_guard()
            self._launcher_generation_guard()
            process = subprocess.Popen(argv, stdin=subprocess.DEVNULL, stdout=subprocess.PIPE,
                                       stderr=subprocess.PIPE, close_fds=True)
            self.evidence.write(stem + "-child.json", _encode({"pid": process.pid,
                "role": role, "identityScope": "original Popen CLI child; no installer/inferior birth attestation"}))
            with selectors.DefaultSelector() as selector:
                for name, pipe in (("stdout", process.stdout), ("stderr", process.stderr)):
                    os.set_blocking(pipe.fileno(), False)
                    selector.register(pipe, selectors.EVENT_READ, name)
                while selector.get_map():
                    if time.monotonic() >= deadline:
                        failure = "timeout"
                        break
                    for key, _ in selector.select(min(0.1, max(0.0, deadline - time.monotonic()))):
                        name = key.data
                        raw = os.read(key.fileobj.fileno(), CHUNK)
                        if not raw:
                            eof[name] = True
                            selector.unregister(key.fileobj)
                            continue
                        # Durably retain the actual bounded prefix even on overflow.
                        remaining = CAP - sum(len(v) for v in output.values())
                        retained = raw[:remaining]
                        if retained:
                            output[name].extend(retained)
                            while len(output[name]) - committed[name] >= CHUNK:
                                chunk = bytes(output[name][committed[name]:committed[name] + CHUNK])
                                parts[name].append(self.evidence.write(f"{stem}-{name}-{len(parts[name]):04d}.raw", chunk))
                                committed[name] += CHUNK
                        if len(raw) > remaining:
                            failure = "output-cap"
                            break
                    if failure:
                        break
            if failure is None:
                rc = process.wait(timeout=max(0.001, deadline - time.monotonic()))
        except subprocess.TimeoutExpired:
            failure = "timeout"
        except (OSError, ValueError):
            failure = "capture-error"
        finally:
            self.capture_partial = {name: bytes(raw) for name, raw in output.items()}
            primary_active = sys.exc_info()[0] is not None
            if process is not None:
                try:
                    if process.poll() is None:
                        process.kill()  # Original Popen child only, never an installer job/PG.
                    rc = process.wait(timeout=5)
                except BaseException:
                    self.sticky_unknown = True
                    self.capture_cleanup_failed = True
                    if not primary_active:
                        raise
                finally:
                    for pipe in (process.stdout, process.stderr):
                        try:
                            pipe.close()
                        except BaseException:
                            self.sticky_unknown = True
                            self.capture_cleanup_failed = True
                            if not primary_active:
                                raise
        for name in ("stdout", "stderr"):
            if committed[name] < len(output[name]):
                chunk = bytes(output[name][committed[name]:])
                parts[name].append(self.evidence.write(f"{stem}-{name}-{len(parts[name]):04d}.raw", chunk))
        if failure is not None:
            self.sticky_unknown = True
        try:
            self._launcher_guard()
        except (OSError, FixtureError):
            failure = failure or "closing-source"
            self.sticky_unknown = True
        manifest = {"schema": 1, "correlationId": self.correlation, "argv": argv, "parts": parts,
            "stdoutSize": len(output["stdout"]), "stderrSize": len(output["stderr"]),
            "stdoutSha256": hashlib.sha256(output["stdout"]).hexdigest(),
            "stderrSha256": hashlib.sha256(output["stderr"]).hexdigest(), "returncode": rc,
            "stdoutEof": eof["stdout"], "stderrEof": eof["stderr"], "failure": failure,
            "childPid": process.pid if process is not None else None, "jobCleanupProven": False,
            "jobReplayAllowed": False, "nativeAcceptanceGranted": False}
        raw_manifest = _encode(manifest)
        self.evidence.write(stem + "-raw-terminal.json", raw_manifest)
        record = RawRecord(tuple(argv), bytes(output["stdout"]), bytes(output["stderr"]), rc,
            eof["stdout"], eof["stderr"], failure, manifest["childPid"],
            self.evidence.path / (stem + "-raw-terminal.json"), hashlib.sha256(raw_manifest).hexdigest())
        self.records.append(record)
        return record

    def _json(self, argv: list[str]) -> dict:
        record = self._capture(argv)
        try:
            self.evidence.body_guard()
            self._launcher_guard()
            self.evidence.generation_guard()
            self._launcher_generation_guard()
        except (OSError, FixtureError):
            self.sticky_unknown = True
            raise FixtureError("direct_capture_closing_unknown") from None
        if record.failure is not None or record.returncode != 0 or not record.stdout_eof or not record.stderr_eof:
            self.sticky_unknown = True
            raise FixtureError("direct_capture_command_unknown")
        try:
            value = json.loads(record.stdout.decode("utf-8", "strict"))
        except (UnicodeError, json.JSONDecodeError):
            self.sticky_unknown = True
            raise FixtureError("direct_capture_public_json") from None
        if type(value) is not dict:
            self.sticky_unknown = True
            raise FixtureError("direct_capture_public_json")
        if value.get("controllerId") != self.controller_id:
            self.sticky_unknown = True
            raise FixtureError("direct_capture_controller_changed")
        return value

    def public(self, app: Path, state_dir: Path, *args: str) -> dict:
        if Path(app) != self.app or Path(state_dir) != self.state_dir:
            raise FixtureError("direct_capture_public_scope")
        return super().public(app, state_dir, *args)

    def close(self) -> None:
        if getattr(self, "launcher_fd", -1) >= 0:
            os.close(self.launcher_fd)
            self.launcher_fd = -1
        for fd, _, _ in getattr(self, "launcher_chain", []):
            os.close(fd)
        self.launcher_chain = []
        self.evidence.close()


def returned_gui_observation(launcher: str, state_dir: str, prior: ProcessIdentity,
                            raw_ps: bytes, status_record: RawRecord, controller_id: str,
                            job_id: str) -> dict:
    """Pure observation, not a visual verdict, package proof or fresh admission.

    raw_ps must come from a separately durably captured guest ps snapshot. Visible
    Aqua window and package/receipt/source/boot/resource proof remain caller gates.
    """
    _uuid(controller_id)
    _uuid(job_id)
    if type(raw_ps) is not bytes or len(raw_ps) > CAP or type(prior) is not ProcessIdentity:
        raise FixtureError("direct_gui_snapshot")
    expected_argv = (launcher, "--state-dir", state_dir, "--json", "updates", "status")
    if type(status_record) is not RawRecord or status_record.argv != expected_argv or status_record.failure is not None or \
            type(status_record.returncode) is not int or status_record.returncode != 0 or \
            status_record.stdout_eof is not True or status_record.stderr_eof is not True:
        raise FixtureError("direct_gui_public_record")
    try:
        lines = raw_ps.decode("utf-8", "strict").splitlines()
        rows = process_rows("\n".join(lines))
        status = json.loads(status_record.stdout.decode("utf-8", "strict"))
    except (UnicodeError, ValueError):
        raise FixtureError("direct_gui_snapshot") from None
    if len(rows) != len(lines) or len({row.pid for row in rows}) != len(rows):
        raise FixtureError("direct_gui_process_catalogue")
    observer = FixtureProcessObserver(launcher, state_dir)
    if prior.argv not in (observer.expected_argv("initial-serve-owner"), observer.expected_argv("plain-return-gui")):
        raise FixtureError("direct_gui_prior_identity")
    gui = observer.returned_gui_after(rows, prior)
    if gui is None:
        raise FixtureError("direct_gui_generation")
    from scripts.macos_aqua_authorization_correlation import public_recovery
    if type(status) is not dict or status.get("controllerId") != controller_id or \
            public_recovery(status, job_id).get("terminal") is not True:
        raise FixtureError("direct_gui_terminal")
    return {"schema": 1, "guiPid": gui.pid, "guiStart": gui.started,
        "controllerId": controller_id, "jobId": job_id, "processSnapshotSha256": hashlib.sha256(raw_ps).hexdigest(),
        "statusRawSha256": hashlib.sha256(status_record.stdout).hexdigest(),
        "observationOnly": True, "visibleAquaWindowProven": False,
        "packageIdentityProven": False, "nativeAcceptanceGranted": False}
