"""Second, separately correlated CP117 public-status one-shot.

It is admitted only after the original attempt is terminally absent.  Its
bootstrap is generated by the reviewed helper for the sole retry task name and
uses the fixed account form after translating it to the original SID.
"""
from __future__ import annotations
import fcntl,hashlib,json,os,stat
from pathlib import Path
from typing import Any,Mapping
from . import windows_msi_owner_public_status as first

class WindowsMsiOwnerPublicStatusRetryError(ValueError):pass
_CORRELATION='f466c4e0-32fa-43b6-bb92-b6f943ca2fe6';_GROUP='.rag_index/windows-msi-owner-public-status-retry';_UNKNOWN={'state':'unknown','replayAllowed':False,'nativeActionAllowed':False}

# This is deliberately a separate, read-only QGA operation.  The original
# diagnostic proves the private-path gates; this adds the scheduler and account
# facts which were the plausible cause of the first task remaining absent.
_PREFLIGHT = first.base._QGA + r'''import time
sock,pid,ticks,sid=sys.argv[1:]
def ps(script):return base64.b64encode(script.encode('utf-16le')).decode()
def out(v):print(json.dumps(v,separators=(',',':'),sort_keys=True))
try:
 if not live(sock,pid,ticks):raise ValueError()
 program=r"""$ErrorActionPreference='Stop';$gate='system-identity'
try{
 if([Security.Principal.WindowsIdentity]::GetCurrent().User.Value -cne 'S-1-5-18'){throw 'SYSTEM'}
 $gate='scheduler';if((Get-Service -Name Schedule -ErrorAction Stop).Status.ToString() -cne 'Running'){throw 'SCHEDULER'}
 $gate='account';$account='VPNMSIX64\vpncp117';$resolved=([Security.Principal.NTAccount]::new($account)).Translate([Security.Principal.SecurityIdentifier]).Value;if($resolved -cne '__SID__'){throw 'ACCOUNT'}
 $gate='session';$count=0;foreach($p in @(Get-CimInstance Win32_Process -Filter "Name='explorer.exe'" -ErrorAction Stop)){if($p.SessionId -eq 1){$o=Invoke-CimMethod -InputObject $p -MethodName GetOwnerSid -ErrorAction Stop;if($o.ReturnValue -eq 0 -and $o.Sid -ceq '__SID__'){$count++}}};if($count -ne 1){throw 'SESSION'}
 $gate='task';if($null -ne (Get-ScheduledTask -TaskName 'VpnControlCp117OwnerPublicStatusC32' -ErrorAction SilentlyContinue)){throw 'ORIGINAL_TASK'};if($null -ne (Get-ScheduledTask -TaskName 'VpnControlCp117OwnerPublicStatusRetryC32' -ErrorAction SilentlyContinue)){throw 'RETRY_TASK'}
 [Console]::Out.WriteLine('{"version":1,"state":"ready","gate":"ready"}')
}catch{[Console]::Out.WriteLine((@{version=1;state='blocked';gate=$gate}|ConvertTo-Json -Compress))}""".replace('__SID__',sid)
 child=call(sock,'guest-exec',{'path':'powershell.exe','arg':['-NoProfile','-NonInteractive','-EncodedCommand',ps(program)],'capture-output':True}).get('pid')
 if type(child) is not int or child<=0:raise ValueError()
 for _ in range(160):
  seen=call(sock,'guest-exec-status',{'pid':child})
  if seen.get('exited') is True:break
  if seen.get('exited') is not False:raise ValueError()
  time.sleep(.25)
 else:raise ValueError()
 if seen.get('exitcode')!=0 or seen.get('out-truncated') is True:raise ValueError()
 raw=base64.b64decode(seen.get('out-data',''),validate=True);lines=[x for x in decode(raw).splitlines() if x.startswith('{') and x.endswith('}')]
 if len(lines)!=1:raise ValueError()
 value=json.loads(lines[0])
 if not isinstance(value,dict) or set(value)!={'version','state','gate'} or value.get('version')!=1 or value.get('state') not in {'ready','blocked'} or value.get('gate') not in {'ready','system-identity','scheduler','account','session','task'}:raise ValueError()
 out(value)
except Exception:out({'version':1,'state':'unknown','gate':'unknown'})
'''

def _dir(root:Path,create:bool)->Path:
 p=root/_GROUP
 if create:p.mkdir(mode=0o700,parents=True,exist_ok=True)
 i=p.lstat()
 if not stat.S_ISDIR(i.st_mode) or p.is_symlink() or i.st_uid!=os.getuid() or stat.S_IMODE(i.st_mode)!=0o700:raise WindowsMsiOwnerPublicStatusRetryError('Unsafe retry journal.')
 return p
def _path(root:Path,create:bool)->Path:return _dir(root,create)/(_CORRELATION+'.json')
def _read(root:Path)->dict|None:
 try:p=_path(root,False)
 except FileNotFoundError:return None
 try:fd=os.open(p,os.O_RDONLY|getattr(os,'O_NOFOLLOW',0))
 except FileNotFoundError:return None
 with os.fdopen(fd,'rb') as s:
  i=os.fstat(s.fileno())
  if not stat.S_ISREG(i.st_mode) or i.st_uid!=os.getuid() or stat.S_IMODE(i.st_mode)!=0o600 or i.st_size>4096:raise WindowsMsiOwnerPublicStatusRetryError('Unsafe retry journal.')
  raw=s.read()
 try:v=json.loads(raw)
 except (ValueError,TypeError):raise WindowsMsiOwnerPublicStatusRetryError('Invalid retry journal.')
 if not isinstance(v,dict) or set(v)!={'version','correlationId','sourceSha','guestGeneration','evidenceSha256','state'} or v.get('version')!=1 or v.get('correlationId')!=_CORRELATION or v.get('sourceSha')!=first.relaunch._SOURCE or v.get('state')!='intent':raise WindowsMsiOwnerPublicStatusRetryError('Invalid retry journal.')
 return v
def _write(root:Path,v:dict)->None:
 d=_dir(root,True);p=_path(root,True);l=os.open(d/'.lock',os.O_RDWR|os.O_CREAT|getattr(os,'O_NOFOLLOW',0),0o600)
 try:
  fcntl.flock(l,fcntl.LOCK_EX)
  if _read(root) is not None:raise WindowsMsiOwnerPublicStatusRetryError('Retry exists.')
  data=(json.dumps(v,sort_keys=True,separators=(',',':'))+'\n').encode();fd=os.open(p,os.O_WRONLY|os.O_CREAT|os.O_EXCL|getattr(os,'O_NOFOLLOW',0),0o600)
  with os.fdopen(fd,'wb') as s:s.write(data);s.flush();os.fsync(s.fileno())
  parent=os.open(d,os.O_RDONLY|getattr(os,'O_DIRECTORY',0));
  try:os.fsync(parent)
  finally:os.close(parent)
 finally:os.close(l)
def _preflight(config:Any,desc:tuple[str,str,int,int,str])->dict|None:
 raw=first.base._remote(config,_PREFLIGHT,(desc[1],str(desc[2]),str(desc[3]),desc[4]),None,60)
 try:v=json.loads(raw) if raw else {}
 except (ValueError,TypeError):return None
 return {'state':v.get('state'),'gate':v.get('gate')} if isinstance(v,dict) and set(v)=={'version','state','gate'} and v.get('version')==1 and v.get('state') in {'ready','blocked','unknown'} and v.get('gate') in {'ready','system-identity','scheduler','account','session','task','unknown'} else None
def _admit(root:Path):
 a=first._admit(root)
 # Original unknown must be explained as an absent original task, never retried.
 old=first.diagnose(root,{'host':'archlinux'})
 if a is None or old!={'state':'diagnosed','phase':'task','task':'absent','replayAllowed':False,'nativeActionAllowed':False}:return None
 config,desc,hash_,gen,evidence=a
 return config,desc,hash_,gen,evidence
def _start_admit(root:Path):
 a=_admit(root)
 if a is None:return None
 return a if _preflight(a[0],a[1])=={'state':'ready','gate':'ready'} else None
def preflight(root:Path|str,inputs:Mapping[str,Any])->dict:
 if not isinstance(inputs,Mapping) or dict(inputs)!={'host':'archlinux'}:raise WindowsMsiOwnerPublicStatusRetryError('Exact CP117 host required.')
 try:
  root=Path(root).resolve();a=_admit(root)
  if a is None:return {'state':'unknown','gate':'unknown','replayAllowed':False,'nativeActionAllowed':False}
  v=_preflight(a[0],a[1])
  if v=={'state':'ready','gate':'ready'}:return {'state':'ready','gate':'ready','replayAllowed':False,'nativeActionAllowed':False}
  if isinstance(v,dict) and v.get('state')=='blocked':return {'state':'blocked','gate':v['gate'],'replayAllowed':False,'nativeActionAllowed':False}
  return {'state':'unknown','gate':'unknown','replayAllowed':False,'nativeActionAllowed':False}
 except (OSError,ValueError,TypeError,KeyError,WindowsMsiOwnerPublicStatusRetryError):return {'state':'unknown','gate':'unknown','replayAllowed':False,'nativeActionAllowed':False}
def start(root:Path|str,inputs:Mapping[str,Any])->dict:
 if not isinstance(inputs,Mapping) or dict(inputs)!={'host':'archlinux'}:raise WindowsMsiOwnerPublicStatusRetryError('Exact CP117 host required.')
 try:
  root=Path(root).resolve()
  if _read(root) is not None:return status(root,inputs)
  a=_start_admit(root)
  if a is None:return dict(_UNKNOWN)
  config,desc,hash_,gen,evidence=a;_write(root,{'version':1,'correlationId':_CORRELATION,'sourceSha':first.relaunch._SOURCE,'guestGeneration':gen,'evidenceSha256':evidence,'state':'intent'})
  return status(root,inputs) if first._run_named(config,desc,hash_,'start',first._RETRY_TASK)=='submitted' else dict(_UNKNOWN)
 except (OSError,ValueError,TypeError,KeyError,WindowsMsiOwnerPublicStatusRetryError):return dict(_UNKNOWN)
def status(root:Path|str,inputs:Mapping[str,Any])->dict:
 if not isinstance(inputs,Mapping) or dict(inputs)!={'host':'archlinux'}:raise WindowsMsiOwnerPublicStatusRetryError('Exact CP117 host required.')
 try:
  root=Path(root).resolve();a=_admit(root);r=_read(root)
  if a is None or r is None:return dict(_UNKNOWN)
  config,desc,hash_,gen,evidence=a
  if r.get('guestGeneration')!=gen or r.get('evidenceSha256')!=evidence:return dict(_UNKNOWN)
  v=first._run_named(config,desc,hash_,'status',first._RETRY_TASK)
  if v=='proved':return {'state':'proved','runtimeRunning':False,'replayAllowed':False,'nativeActionAllowed':False}
  return {'state':'pending','replayAllowed':False,'nativeActionAllowed':False} if v=='pending' else dict(_UNKNOWN)
 except (OSError,ValueError,TypeError,KeyError,WindowsMsiOwnerPublicStatusRetryError):return dict(_UNKNOWN)
def collect(root:Path|str,inputs:Mapping[str,Any])->dict:return status(root,inputs)
def diagnose(root:Path|str,inputs:Mapping[str,Any])->dict:
 """Read the retry task only; never infer permission to submit it again."""
 if not isinstance(inputs,Mapping) or dict(inputs)!={'host':'archlinux'}:raise WindowsMsiOwnerPublicStatusRetryError('Exact CP117 host required.')
 try:
  root=Path(root).resolve();a=_admit(root);r=_read(root)
  if a is None or r is None:return dict(_UNKNOWN)
  config,desc,hash_,gen,evidence=a
  if r.get('guestGeneration')!=gen or r.get('evidenceSha256')!=evidence:return dict(_UNKNOWN)
  found=first._diagnostic_named(config,desc,hash_,first._RETRY_TASK)
  return {'state':'diagnosed',**found,'replayAllowed':False,'nativeActionAllowed':False} if found is not None else dict(_UNKNOWN)
 except (OSError,ValueError,TypeError,KeyError,WindowsMsiOwnerPublicStatusRetryError):return dict(_UNKNOWN)
def _observer_admit(root:Path):
 """Bind a read-only task observer without requiring current owner census."""
 record=_read(root)
 if record is None:return None,'retry-intent'
 admitted=first.relaunch.liveness._admit(root)
 if admitted is None:return None,'base-binding'
 config,desc,source,hash_=admitted
 if source!=first.relaunch._SOURCE or not first.relaunch._SHA256.fullmatch(str(hash_)):return None,'source-hash'
 launch=first.relaunch._read_intent(root)
 if not isinstance(launch,dict):return None,'relaunch-intent'
 gen={'socketPath':desc[1],'qemuPid':desc[2],'startTicks':desc[3]}
 evidence=hashlib.sha256(json.dumps(gen,sort_keys=True).encode()).hexdigest()
 if (launch.get('guestGeneration')!=gen or launch.get('staleRecoveryEvidenceSha256')!=evidence
     or record.get('guestGeneration')!=gen or record.get('evidenceSha256')!=evidence):return None,'generation'
 return (config,desc,hash_),'task-observer'
def retry_diagnostic(root:Path|str,inputs:Mapping[str,Any])->dict:
 """Classify the fixed retry task after a lost response without admitting a retry."""
 if not isinstance(inputs,Mapping) or dict(inputs)!={'host':'archlinux'}:raise WindowsMsiOwnerPublicStatusRetryError('Exact CP117 host required.')
 try:
  root=Path(root).resolve();bound,stage=_observer_admit(root)
  if bound is None:return {'state':'blocked','stage':stage,'replayAllowed':False,'nativeActionAllowed':False}
  found=first._diagnostic_named(*bound,first._RETRY_TASK)
  if found is None:return {'state':'unknown','stage':'task-observer','replayAllowed':False,'nativeActionAllowed':False}
  return {'state':'diagnosed','stage':'task-observer',**found,'replayAllowed':False,'nativeActionAllowed':False}
 except (OSError,ValueError,TypeError,KeyError,WindowsMsiOwnerPublicStatusRetryError):return {'state':'unknown','stage':'task-observer','replayAllowed':False,'nativeActionAllowed':False}
def workflow(root:Path|str,action:str,inputs:Mapping[str,Any])->dict:
 if action=='preflight':return preflight(root,inputs)
 if action=='start':return start(root,inputs)
 if action in {'status','collect'}:return status(root,inputs)
 if action=='diagnose':return diagnose(root,inputs)
 if action=='retry-diagnostic':return retry_diagnostic(root,inputs)
 raise WindowsMsiOwnerPublicStatusRetryError('Unsupported retry action.')
