<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>vpn-control-install-helper</AssemblyName>
    <RootNamespace>VpnControl.InstallHelper</RootNamespace>
    <StartupObject>VpnInstallHelper</StartupObject>
    <ApplicationManifest>loader.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\..\..\src\main\resources\windows-install-native.cs" Link="windows-install-native.cs" />
    <Compile Include="..\..\..\src\main\resources\windows-install-helper.cs" Link="windows-install-helper.cs" />
    <Compile Include="..\..\..\src\main\resources\windows-install-helper-protocol.cs" Link="windows-install-helper-protocol.cs" />
    <Compile Include="..\..\..\src\main\resources\windows-install-helper-roles.cs" Link="windows-install-helper-roles.cs" />
    <Compile Include="..\..\..\src\main\resources\windows-install-helper-msi.cs" Link="windows-install-helper-msi.cs" />
    <Compile Include="..\..\..\src\main\resources\windows-install-helper-sessions.cs" Link="windows-install-helper-sessions.cs" />
  </ItemGroup>
</Project>
